package mei.zero.writer

// This file is auto-generated from MEI RelaxNG schema.
// Do not edit this file manually.

import scala.xml.{Node, Elem, Null, TopScope, UnprefixedAttribute, MetaData}
import mei.zero.*

/** Although this abstraction is not strictly necessary, it is provided to prevent the linter from warning about an unused variable in def toXml for a class that has no fields. */
trait MeiModelDummyWriter[T] {
  def toXml(obj: T): scala.xml.Node
}

object MeiXmlWriter {
  def toXml(obj: Any): Node = obj match {
    case x: FileDesc => FileDescWriter.toXml(x)
    case x: Title => TitleWriter.toXml(x)
    case x: TitleStmt => TitleStmtWriter.toXml(x)
    case x: java.lang.String => scala.xml.Text(x)
    case x: scala.xml.Node => x
    case x: Seq[_] => throw new IllegalArgumentException(s"Seq passed to toXml (should be handled by caller or flattened): $x")
    case _ => scala.xml.Text(obj.toString)
  }
}

object FileDescWriter extends MeiModelDummyWriter[FileDesc] {
  def toXml(obj: FileDesc): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap {
      case x => Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "fileDesc", attributes, TopScope, true, children*)
  }
}

object TitleWriter extends MeiModelDummyWriter[Title] {
  def toXml(obj: Title): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@level`.foreach { v => attributes = new UnprefixedAttribute("level", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap {
      case x => Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "title", attributes, TopScope, true, children*)
  }
}

object TitleStmtWriter extends MeiModelDummyWriter[TitleStmt] {
  def toXml(obj: TitleStmt): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap {
      case x => Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "titleStmt", attributes, TopScope, true, children*)
  }
}

