package mei.minimum.writer

// This file is auto-generated from MEI RelaxNG schema.
// Do not edit this file manually.

import scala.xml.{Node, Elem, Null, TopScope, UnprefixedAttribute, MetaData}
import mei.minimum.*

/** Although this abstraction is not strictly necessary, it is provided to prevent the linter from warning about an unused variable in def toXml for a class that has no fields. */
trait MeiModelDummyWriter[T] {
  def toXml(obj: T): scala.xml.Node
}

object MeiXmlWriter {
  def toXml(obj: Any): Node = obj match {
    case x: Body             => BodyWriter.toXml(x)
    case x: FileDesc         => FileDescWriter.toXml(x)
    case x: Layer            => LayerWriter.toXml(x)
    case x: Mdiv             => MdivWriter.toXml(x)
    case x: Mei              => MeiWriter.toXml(x)
    case x: MeiHead          => MeiHeadWriter.toXml(x)
    case x: Music            => MusicWriter.toXml(x)
    case x: Note             => NoteWriter.toXml(x)
    case x: Score            => ScoreWriter.toXml(x)
    case x: Section          => SectionWriter.toXml(x)
    case x: Staff            => StaffWriter.toXml(x)
    case x: Title            => TitleWriter.toXml(x)
    case x: TitleStmt        => TitleStmtWriter.toXml(x)
    case x: java.lang.String => scala.xml.Text(x)
    case x: scala.xml.Node   => x
    case x: Seq[_]           =>
      throw new IllegalArgumentException(s"Seq passed to toXml (should be handled by caller or flattened): $x")
    case _ => scala.xml.Text(obj.toString)
  }
}

object BodyWriter extends MeiModelDummyWriter[Body] {
  def toXml(obj: Body): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "body", attributes, TopScope, true, children*)
  }
}

object FileDescWriter extends MeiModelDummyWriter[FileDesc] {
  def toXml(obj: FileDesc): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "fileDesc", attributes, TopScope, true, children*)
  }
}

object LayerWriter extends MeiModelDummyWriter[Layer] {
  def toXml(obj: Layer): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }
    obj.`@n`.foreach { v => attributes = new UnprefixedAttribute("n", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@cue`.foreach { v => attributes = new UnprefixedAttribute("cue", v, attributes) }
    obj.`@metcon`.foreach { v => attributes = new UnprefixedAttribute("metcon", v, attributes) }
    obj.`@def`.foreach { v => attributes = new UnprefixedAttribute("def", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "layer", attributes, TopScope, true, children*)
  }
}

object MdivWriter extends MeiModelDummyWriter[Mdiv] {
  def toXml(obj: Mdiv): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "mdiv", attributes, TopScope, true, children*)
  }
}

object MeiWriter extends MeiModelDummyWriter[Mei] {
  def toXml(obj: Mei): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@meiversion`.foreach { v => attributes = new UnprefixedAttribute("meiversion", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "mei", attributes, TopScope, true, children*)
  }
}

object MeiHeadWriter extends MeiModelDummyWriter[MeiHead] {
  def toXml(obj: MeiHead): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@meiversion`.foreach { v => attributes = new UnprefixedAttribute("meiversion", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "meiHead", attributes, TopScope, true, children*)
  }
}

object MusicWriter extends MeiModelDummyWriter[Music] {
  def toXml(obj: Music): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@meiversion`.foreach { v => attributes = new UnprefixedAttribute("meiversion", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "music", attributes, TopScope, true, children*)
  }
}

object NoteWriter extends MeiModelDummyWriter[Note] {
  def toXml(obj: Note): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@dots`.foreach { v => attributes = new UnprefixedAttribute("dots", v, attributes) }
    obj.`@colored`.foreach { v => attributes = new UnprefixedAttribute("colored", v, attributes) }
    obj.`@cue`.foreach { v => attributes = new UnprefixedAttribute("cue", v, attributes) }
    obj.`@dur`.foreach { v => attributes = new UnprefixedAttribute("dur", v, attributes) }
    obj.`@layer`.foreach { v => attributes = new UnprefixedAttribute("layer", v, attributes) }
    obj.`@staff`.foreach { v => attributes = new UnprefixedAttribute("staff", v, attributes) }
    obj.`@tstamp`.foreach { v => attributes = new UnprefixedAttribute("tstamp", v, attributes) }
    obj.`@pname`.foreach { v => attributes = new UnprefixedAttribute("pname", v, attributes) }
    obj.`@oct`.foreach { v => attributes = new UnprefixedAttribute("oct", v, attributes) }

    val children: scala.collection.immutable.List[Node] = scala.collection.immutable.Nil

    Elem(null, "note", attributes, TopScope, true, children*)
  }
}

object ScoreWriter extends MeiModelDummyWriter[Score] {
  def toXml(obj: Score): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "score", attributes, TopScope, true, children*)
  }
}

object SectionWriter extends MeiModelDummyWriter[Section] {
  def toXml(obj: Section): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }
    obj.`@xlink:actuate`.foreach { v => attributes = new UnprefixedAttribute("xlink:actuate", v, attributes) }
    obj.`@xlink:role`.foreach { v => attributes = new UnprefixedAttribute("xlink:role", v, attributes) }
    obj.`@xlink:show`.foreach { v => attributes = new UnprefixedAttribute("xlink:show", v, attributes) }
    obj.`@target`.foreach { v => attributes = new UnprefixedAttribute("target", v, attributes) }
    obj.`@targettype`.foreach { v => attributes = new UnprefixedAttribute("targettype", v, attributes) }
    obj.`@evaluate`.foreach { v => attributes = new UnprefixedAttribute("evaluate", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "section", attributes, TopScope, true, children*)
  }
}

object StaffWriter extends MeiModelDummyWriter[Staff] {
  def toXml(obj: Staff): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@decls`.foreach { v => attributes = new UnprefixedAttribute("decls", v, attributes) }
    obj.`@n`.foreach { v => attributes = new UnprefixedAttribute("n", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }
    obj.`@metcon`.foreach { v => attributes = new UnprefixedAttribute("metcon", v, attributes) }
    obj.`@def`.foreach { v => attributes = new UnprefixedAttribute("def", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "staff", attributes, TopScope, true, children*)
  }
}

object TitleWriter extends MeiModelDummyWriter[Title] {
  def toXml(obj: Title): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@level`.foreach { v => attributes = new UnprefixedAttribute("level", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "title", attributes, TopScope, true, children*)
  }
}

object TitleStmtWriter extends MeiModelDummyWriter[TitleStmt] {
  def toXml(obj: TitleStmt): Elem = {
    var attributes: MetaData = Null
    obj.`@xml:id`.foreach { v => attributes = new UnprefixedAttribute("xml:id", v, attributes) }
    obj.`@xml:base`.foreach { v => attributes = new UnprefixedAttribute("xml:base", v, attributes) }
    obj.`@class`.foreach { v => attributes = new UnprefixedAttribute("class", v, attributes) }
    obj.`@type`.foreach { v => attributes = new UnprefixedAttribute("type", v, attributes) }

    val children: scala.collection.immutable.List[Node] = obj.elements.flatMap { case x =>
      Some(MeiXmlWriter.toXml(x))
    }

    Elem(null, "titleStmt", attributes, TopScope, true, children*)
  }
}
