package mei.zero.parser

// This file is auto-generated from MEI RelaxNG schema.
// Do not edit this file manually.

import scala.xml.{Node, NodeSeq, Elem}
import mei.zero.*

/** Although this abstraction is not strictly necessary, it is provided to prevent the linter from warning about an unused variable in def parse for a class that has no fields. */
trait MeiModelDummyParser {
  def parse(node: Node): Any
}

object FileDescParser extends MeiModelDummyParser {
  def parse(node: Node): FileDesc = {
    FileDesc(
      node.child.collect {
        case n: Elem if n.label == "titleStmt" => mei.zero.parser.TitleStmtParser.parse(n)
      }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
    )
  }
}
object TitleStmtParser extends MeiModelDummyParser {
  def parse(node: Node): TitleStmt = {
    TitleStmt(
      node.child.collect {
        case n: Elem if n.label == "title" => mei.zero.parser.TitleParser.parse(n)
      }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
    )
  }
}
object TitleParser extends MeiModelDummyParser {
  def parse(node: Node): Title = {
    Title(
      node.child.collect {
        case n if n.text.trim.nonEmpty => n.text
      }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("level").map(_.text),
      node.attribute("type").map(_.text),
    )
  }
}
