package mei.minimum.parser

// This file is auto-generated from MEI RelaxNG schema.
// Do not edit this file manually.

import scala.xml.{Node, NodeSeq, Elem}
import mei.minimum.*

/** Although this abstraction is not strictly necessary, it is provided to prevent the linter from warning about an unused variable in def parse for a class that has no fields. */
trait MeiModelDummyParser {
  def parse(node: Node): Any
}

object FileDescParser extends MeiModelDummyParser {
  def parse(node: Node): FileDesc = {
    FileDesc(
      node.child.collect {
        case n: Elem if n.label == "titleStmt" => mei.minimum.parser.TitleStmtParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text)
    )
  }
}
object MeiHeadParser extends MeiModelDummyParser {
  def parse(node: Node): MeiHead = {
    MeiHead(
      node.child.collect {
        case n: Elem if n.label == "fileDesc" => mei.minimum.parser.FileDescParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("meiversion").map(_.text),
      node.attribute("type").map(_.text)
    )
  }
}
object TitleStmtParser extends MeiModelDummyParser {
  def parse(node: Node): TitleStmt = {
    TitleStmt(
      node.child.collect {
        case n: Elem if n.label == "title" => mei.minimum.parser.TitleParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text)
    )
  }
}
object BodyParser extends MeiModelDummyParser {
  def parse(node: Node): Body = {
    Body(
      node.child.collect {
        case n: Elem if n.label == "mdiv" => mei.minimum.parser.MdivParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("decls").map(_.text)
    )
  }
}
object LayerParser extends MeiModelDummyParser {
  def parse(node: Node): Layer = {
    Layer(
      node.child.collect {
        case n: Elem if n.label == "note" => mei.minimum.parser.NoteParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("decls").map(_.text),
      node.attribute("n").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("cue").map(_.text),
      node.attribute("metcon").map(_.text),
      node.attribute("def").map(_.text)
    )
  }
}
object MdivParser extends MeiModelDummyParser {
  def parse(node: Node): Mdiv = {
    Mdiv(
      node.child.collect {
        case n: Elem if n.label == "mdiv" => mei.minimum.parser.MdivParser.parse(n)
        case n: Elem if n.label == "score" => mei.minimum.parser.ScoreParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("decls").map(_.text)
    )
  }
}
object MeiParser extends MeiModelDummyParser {
  def parse(node: Node): Mei = {
    Mei(
      node.child.collect {
        case n: Elem if n.label == "meiHead" => mei.minimum.parser.MeiHeadParser.parse(n)
        case n: Elem if n.label == "music" => mei.minimum.parser.MusicParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("meiversion").map(_.text)
    )
  }
}
object MusicParser extends MeiModelDummyParser {
  def parse(node: Node): Music = {
    Music(
      node.child.collect {
        case n: Elem if n.label == "body" => mei.minimum.parser.BodyParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("meiversion").map(_.text),
      node.attribute("decls").map(_.text)
    )
  }
}
object NoteParser extends MeiModelDummyParser {
  def parse(node: Node): Note = {
    Note(
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("dots").map(_.text),
      node.attribute("colored").map(_.text),
      node.attribute("cue").map(_.text),
      node.attribute("dur").map(_.text),
      node.attribute("layer").map(_.text),
      node.attribute("staff").map(_.text),
      node.attribute("tstamp").map(_.text),
      node.attribute("pname").map(_.text),
      node.attribute("oct").map(_.text)
    )
  }
}
object ScoreParser extends MeiModelDummyParser {
  def parse(node: Node): Score = {
    Score(
      node.child.collect {
        case n: Elem if n.label == "section" => mei.minimum.parser.SectionParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("decls").map(_.text)
    )
  }
}
object SectionParser extends MeiModelDummyParser {
  def parse(node: Node): Section = {
    Section(
      node.child.collect {
        case n: Elem if n.label == "section" => mei.minimum.parser.SectionParser.parse(n)
        case n: Elem if n.label == "staff" => mei.minimum.parser.StaffParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("decls").map(_.text),
      node.attribute("xlink:actuate").map(_.text),
      node.attribute("xlink:role").map(_.text),
      node.attribute("xlink:show").map(_.text),
      node.attribute("target").map(_.text),
      node.attribute("targettype").map(_.text),
      node.attribute("evaluate").map(_.text)
    )
  }
}
object StaffParser extends MeiModelDummyParser {
  def parse(node: Node): Staff = {
    Staff(
      node.child.collect {
        case n: Elem if n.label == "layer" => mei.minimum.parser.LayerParser.parse(n)        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("decls").map(_.text),
      node.attribute("n").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("type").map(_.text),
      node.attribute("metcon").map(_.text),
      node.attribute("def").map(_.text)
    )
  }
}
object TitleParser extends MeiModelDummyParser {
  def parse(node: Node): Title = {
    Title(
      node.child.collect {
        case n if n.text.trim.nonEmpty => n.text        }.toList,
      node.attribute("xml:id").map(_.text),
      node.attribute("xml:base").map(_.text),
      node.attribute("class").map(_.text),
      node.attribute("level").map(_.text),
      node.attribute("type").map(_.text)
    )
  }
}
