package mei.zero

// This file is auto-generated from MEI RelaxNG schema.
// Do not edit this file manually.

/** data.URI
  */
type DataURI = java.lang.String

/** <fileDesc>
  *
  * (file description) Contains a full bibliographic description of the MEI file.
  */
case class FileDesc(
    /** <fileDesc> -> titleStmt -> <titleStmt> (-> TitleStmt)
      */
    elements: scala.List[TitleStmt] = scala.Nil,
    /** Regularizes the naming of an element and thus facilitates building links between it and other resources. Each id attribute within a document must have a unique value.
      * 
      * <fileDesc> -> att.common -> att.basic -> att.id -> att.id.xmlid -> @xml:id
      */
    `@xml:id`: scala.Option[java.lang.String] = scala.None,
    /** Provides a base URI reference with which applications can resolve relative URI references into absolute URI references.
      * 
      * <fileDesc> -> att.common -> att.basic -> att.basic.xmlbase -> @xml:base
      */
    `@xml:base`: scala.Option[DataURI] = scala.None,
    /** Contains one or more URIs which denote classification terms that apply to the entity bearing this attribute.
      * 
      * <fileDesc> -> att.common -> att.typed -> att.classed -> att.classed.class -> @class
      */
    `@class`: scala.Option[java.lang.String] = scala.None,
    /** Designation which characterizes the element in some sense, using any convenient classification scheme or typology that employs single-token labels.
      * 
      * <fileDesc> -> att.common -> att.typed -> att.typed.type -> @type
      */
    `@type`: scala.Option[java.lang.String] = scala.None
)

/** <titleStmt>
  *
  * (title statement) Container for title and responsibility meta-data.
  */
case class TitleStmt(
    /** <titleStmt> -> model.titleLike -> title -> <title> (-> Title)
      */
    elements: scala.List[Title] = scala.Nil,
    /** Regularizes the naming of an element and thus facilitates building links between it and other resources. Each id attribute within a document must have a unique value.
      * 
      * <titleStmt> -> att.common -> att.basic -> att.id -> att.id.xmlid -> @xml:id
      */
    `@xml:id`: scala.Option[java.lang.String] = scala.None,
    /** Provides a base URI reference with which applications can resolve relative URI references into absolute URI references.
      * 
      * <titleStmt> -> att.common -> att.basic -> att.basic.xmlbase -> @xml:base
      */
    `@xml:base`: scala.Option[DataURI] = scala.None,
    /** Contains one or more URIs which denote classification terms that apply to the entity bearing this attribute.
      * 
      * <titleStmt> -> att.common -> att.typed -> att.classed -> att.classed.class -> @class
      */
    `@class`: scala.Option[java.lang.String] = scala.None,
    /** Designation which characterizes the element in some sense, using any convenient classification scheme or typology that employs single-token labels.
      * 
      * <titleStmt> -> att.common -> att.typed -> att.typed.type -> @type
      */
    `@type`: scala.Option[java.lang.String] = scala.None
)

/** <title>
  *
  * Title of a bibliographic entity.
  */
case class Title(
    /** <title> -> text (-> java.lang.String)
      */
    elements: scala.List[java.lang.String] = scala.Nil,
    /** Regularizes the naming of an element and thus facilitates building links between it and other resources. Each id attribute within a document must have a unique value.
      * 
      * <title> -> att.basic -> att.id -> att.id.xmlid -> @xml:id
      */
    `@xml:id`: scala.Option[java.lang.String] = scala.None,
    /** Provides a base URI reference with which applications can resolve relative URI references into absolute URI references.
      * 
      * <title> -> att.basic -> att.basic.xmlbase -> @xml:base
      */
    `@xml:base`: scala.Option[DataURI] = scala.None,
    /** Contains one or more URIs which denote classification terms that apply to the entity bearing this attribute.
      * 
      * <title> -> att.classed -> att.classed.class -> @class
      */
    `@class`: scala.Option[java.lang.String] = scala.None,
    /** Indicates the bibliographic level of the title.
      * 
      * <title> -> @level
      */
    `@level`: scala.Option[java.lang.String] = scala.None,
    /** Characterizes the title in some sense, using any convenient classification scheme or typology that employs single-token labels.
      * Suggested values include: 1] main; 2] subordinate; 3] abbreviated; 4] alternative; 5] translated; 6] uniform; 7] desc
      * 
      * <title> -> @type
      */
    `@type`: scala.Option[java.lang.String] = scala.None
)

