package meibasic

import scala.xml.*

object MeiXML {

  def load(xml: Elem): meibasic.mei.shared.Mei = {
    loadElement(xml) match {
      case m: meibasic.mei.shared.Mei => m
      case other => throw new IllegalArgumentException(s"Root element must be 'mei', but got ${other.getClass.getSimpleName}")
    }
  }

  def loadElement(node: Node): meibasic.Element = node match {
    case e: Elem =>
      val attributes: scala.collection.immutable.SeqMap[String, String] = scala.collection.immutable.SeqMap.from(
        e.attributes.map {
          case p: scala.xml.PrefixedAttribute => (s"${p.pre}:${p.key}", p.value.text)
          case u: scala.xml.UnprefixedAttribute => (u.key, u.value.text)
          case m => (m.key, m.value.text)
        }
      )
      val children = e.child.flatMap(n => Option(loadElement(n))).toList
      
      e.label match {
      case "accid" => meibasic.mei.shared.Accid(children, attributes)
      case "arpeg" => meibasic.mei.cmn.Arpeg(children, attributes)
      case "arranger" => meibasic.mei.shared.Arranger(children, attributes)
      case "artic" => meibasic.mei.shared.Artic(children, attributes)
      case "availability" => meibasic.mei.header.Availability(children, attributes)
      case "bTrem" => meibasic.mei.cmn.BTrem(children, attributes)
      case "barre" => meibasic.mei.stringtab.Barre(children, attributes)
      case "beam" => meibasic.mei.cmn.Beam(children, attributes)
      case "beatRpt" => meibasic.mei.cmn.BeatRpt(children, attributes)
      case "body" => meibasic.mei.shared.Body(children, attributes)
      case "breath" => meibasic.mei.cmn.Breath(children, attributes)
      case "caesura" => meibasic.mei.shared.Caesura(children, attributes)
      case "chord" => meibasic.mei.shared.Chord(children, attributes)
      case "chordDef" => meibasic.mei.harmony.ChordDef(children, attributes)
      case "chordMember" => meibasic.mei.harmony.ChordMember(children, attributes)
      case "chordTable" => meibasic.mei.harmony.ChordTable(children, attributes)
      case "clef" => meibasic.mei.shared.Clef(children, attributes)
      case "clefGrp" => meibasic.mei.shared.ClefGrp(children, attributes)
      case "composer" => meibasic.mei.shared.Composer(children, attributes)
      case "course" => meibasic.mei.stringtab.Course(children, attributes)
      case "date" => meibasic.mei.shared.Date(children, attributes)
      case "dir" => meibasic.mei.shared.Dir(children, attributes)
      case "dynam" => meibasic.mei.shared.Dynam(children, attributes)
      case "ending" => meibasic.mei.shared.Ending(children, attributes)
      case "f" => meibasic.mei.harmony.F(children, attributes)
      case "fTrem" => meibasic.mei.cmn.FTrem(children, attributes)
      case "fb" => meibasic.mei.harmony.Fb(children, attributes)
      case "fermata" => meibasic.mei.cmn.Fermata(children, attributes)
      case "fileDesc" => meibasic.mei.header.FileDesc(children, attributes)
      case "fing" => meibasic.mei.fingering.Fing(children, attributes)
      case "fingGrp" => meibasic.mei.fingering.FingGrp(children, attributes)
      case "gliss" => meibasic.mei.cmn.Gliss(children, attributes)
      case "graceGrp" => meibasic.mei.cmn.GraceGrp(children, attributes)
      case "hairpin" => meibasic.mei.cmn.Hairpin(children, attributes)
      case "halfmRpt" => meibasic.mei.cmn.HalfmRpt(children, attributes)
      case "harm" => meibasic.mei.harmony.Harm(children, attributes)
      case "harpPedal" => meibasic.mei.cmn.HarpPedal(children, attributes)
      case "instrDef" => meibasic.mei.midi.InstrDef(children, attributes)
      case "label" => meibasic.mei.shared.Label(children, attributes)
      case "labelAbbr" => meibasic.mei.shared.LabelAbbr(children, attributes)
      case "layer" => meibasic.mei.shared.Layer(children, attributes)
      case "lb" => meibasic.mei.shared.Lb(children, attributes)
      case "lv" => meibasic.mei.cmn.Lv(children, attributes)
      case "lyricist" => meibasic.mei.shared.Lyricist(children, attributes)
      case "mNum" => meibasic.mei.cmn.MNum(children, attributes)
      case "mRest" => meibasic.mei.cmn.MRest(children, attributes)
      case "mRpt" => meibasic.mei.cmn.MRpt(children, attributes)
      case "mdiv" => meibasic.mei.shared.Mdiv(children, attributes)
      case "measure" => meibasic.mei.cmn.Measure(children, attributes)
      case "mei" => meibasic.mei.shared.Mei(children, attributes)
      case "meiHead" => meibasic.mei.header.MeiHead(children, attributes)
      case "mordent" => meibasic.mei.cmnornaments.Mordent(children, attributes)
      case "multiRest" => meibasic.mei.cmn.MultiRest(children, attributes)
      case "multiRpt" => meibasic.mei.cmn.MultiRpt(children, attributes)
      case "music" => meibasic.mei.shared.Music(children, attributes)
      case "note" => meibasic.mei.shared.Note(children, attributes)
      case "octave" => meibasic.mei.cmn.Octave(children, attributes)
      case "ornam" => meibasic.mei.shared.Ornam(children, attributes)
      case "pb" => meibasic.mei.shared.Pb(children, attributes)
      case "pedal" => meibasic.mei.cmn.Pedal(children, attributes)
      case "persName" => meibasic.mei.namesdates.PersName(children, attributes)
      case "pgFoot" => meibasic.mei.shared.PgFoot(children, attributes)
      case "pgHead" => meibasic.mei.shared.PgHead(children, attributes)
      case "pubPlace" => meibasic.mei.shared.PubPlace(children, attributes)
      case "pubStmt" => meibasic.mei.header.PubStmt(children, attributes)
      case "refrain" => meibasic.mei.lyrics.Refrain(children, attributes)
      case "reh" => meibasic.mei.cmn.Reh(children, attributes)
      case "rend" => meibasic.mei.shared.Rend(children, attributes)
      case "repeatMark" => meibasic.mei.cmn.RepeatMark(children, attributes)
      case "respStmt" => meibasic.mei.shared.RespStmt(children, attributes)
      case "rest" => meibasic.mei.shared.Rest(children, attributes)
      case "sb" => meibasic.mei.shared.Sb(children, attributes)
      case "score" => meibasic.mei.shared.Score(children, attributes)
      case "scoreDef" => meibasic.mei.shared.ScoreDef(children, attributes)
      case "section" => meibasic.mei.shared.Section(children, attributes)
      case "slur" => meibasic.mei.cmn.Slur(children, attributes)
      case "space" => meibasic.mei.shared.Space(children, attributes)
      case "staff" => meibasic.mei.shared.Staff(children, attributes)
      case "staffDef" => meibasic.mei.shared.StaffDef(children, attributes)
      case "staffGrp" => meibasic.mei.shared.StaffGrp(children, attributes)
      case "string" => meibasic.mei.stringtab.String(children, attributes)
      case "syl" => meibasic.mei.shared.Syl(children, attributes)
      case "symbol" => meibasic.mei.shared.Symbol(children, attributes)
      case "tabDurSym" => meibasic.mei.stringtab.TabDurSym(children, attributes)
      case "tabGrp" => meibasic.mei.stringtab.TabGrp(children, attributes)
      case "tempo" => meibasic.mei.shared.Tempo(children, attributes)
      case "tie" => meibasic.mei.cmn.Tie(children, attributes)
      case "title" => meibasic.mei.shared.Title(children, attributes)
      case "titleStmt" => meibasic.mei.header.TitleStmt(children, attributes)
      case "trill" => meibasic.mei.cmnornaments.Trill(children, attributes)
      case "tuplet" => meibasic.mei.cmn.Tuplet(children, attributes)
      case "turn" => meibasic.mei.cmnornaments.Turn(children, attributes)
      case "verse" => meibasic.mei.lyrics.Verse(children, attributes)
      case "volta" => meibasic.mei.lyrics.Volta(children, attributes)
        case _ => throw new IllegalArgumentException(s"Unknown tag: ${e.label}")
      }

    case t: scala.xml.Text => meibasic.Text(t.text)
    case _ => null // Ignore comments, etc.
  } 
  
  private def mkAttributes(attributes: scala.collection.immutable.SeqMap[String, String]): MetaData = {
    attributes.foldRight[MetaData](Null) { case ((k, v), acc) =>
      if (k.contains(":")) {
        val parts = k.split(":", 2)
        new PrefixedAttribute(parts(0), parts(1), v, acc)
      } else {
        new UnprefixedAttribute(k, v, acc)
      }
    }
  }

  private val meiScope = scala.xml.NamespaceBinding(null, "http://www.music-encoding.org/ns/mei", scala.xml.TopScope)

  def toXml(element: meibasic.Element): Node = toXmlWithScope(element, meiScope)

  private def toXmlWithScope(element: meibasic.Element, scope: NamespaceBinding): Node = element match {
    case meibasic.Text(value) => scala.xml.Text(value)
    case e: meibasic.mei.shared.Accid => new scala.xml.Elem(null, "accid", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Arpeg => new scala.xml.Elem(null, "arpeg", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Arranger => new scala.xml.Elem(null, "arranger", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Artic => new scala.xml.Elem(null, "artic", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.header.Availability => new scala.xml.Elem(null, "availability", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.BTrem => new scala.xml.Elem(null, "bTrem", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.stringtab.Barre => new scala.xml.Elem(null, "barre", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Beam => new scala.xml.Elem(null, "beam", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.BeatRpt => new scala.xml.Elem(null, "beatRpt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Body => new scala.xml.Elem(null, "body", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Breath => new scala.xml.Elem(null, "breath", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Caesura => new scala.xml.Elem(null, "caesura", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Chord => new scala.xml.Elem(null, "chord", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.ChordDef => new scala.xml.Elem(null, "chordDef", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.ChordMember => new scala.xml.Elem(null, "chordMember", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.ChordTable => new scala.xml.Elem(null, "chordTable", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Clef => new scala.xml.Elem(null, "clef", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.ClefGrp => new scala.xml.Elem(null, "clefGrp", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Composer => new scala.xml.Elem(null, "composer", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.stringtab.Course => new scala.xml.Elem(null, "course", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Date => new scala.xml.Elem(null, "date", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Dir => new scala.xml.Elem(null, "dir", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Dynam => new scala.xml.Elem(null, "dynam", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Ending => new scala.xml.Elem(null, "ending", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.F => new scala.xml.Elem(null, "f", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.FTrem => new scala.xml.Elem(null, "fTrem", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.Fb => new scala.xml.Elem(null, "fb", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Fermata => new scala.xml.Elem(null, "fermata", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.header.FileDesc => new scala.xml.Elem(null, "fileDesc", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.fingering.Fing => new scala.xml.Elem(null, "fing", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.fingering.FingGrp => new scala.xml.Elem(null, "fingGrp", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Gliss => new scala.xml.Elem(null, "gliss", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.GraceGrp => new scala.xml.Elem(null, "graceGrp", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Hairpin => new scala.xml.Elem(null, "hairpin", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.HalfmRpt => new scala.xml.Elem(null, "halfmRpt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.harmony.Harm => new scala.xml.Elem(null, "harm", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.HarpPedal => new scala.xml.Elem(null, "harpPedal", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.midi.InstrDef => new scala.xml.Elem(null, "instrDef", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Label => new scala.xml.Elem(null, "label", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.LabelAbbr => new scala.xml.Elem(null, "labelAbbr", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Layer => new scala.xml.Elem(null, "layer", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Lb => new scala.xml.Elem(null, "lb", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Lv => new scala.xml.Elem(null, "lv", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Lyricist => new scala.xml.Elem(null, "lyricist", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.MNum => new scala.xml.Elem(null, "mNum", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.MRest => new scala.xml.Elem(null, "mRest", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.MRpt => new scala.xml.Elem(null, "mRpt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Mdiv => new scala.xml.Elem(null, "mdiv", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Measure => new scala.xml.Elem(null, "measure", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Mei => new scala.xml.Elem(null, "mei", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.header.MeiHead => new scala.xml.Elem(null, "meiHead", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmnornaments.Mordent => new scala.xml.Elem(null, "mordent", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.MultiRest => new scala.xml.Elem(null, "multiRest", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.MultiRpt => new scala.xml.Elem(null, "multiRpt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Music => new scala.xml.Elem(null, "music", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Note => new scala.xml.Elem(null, "note", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Octave => new scala.xml.Elem(null, "octave", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Ornam => new scala.xml.Elem(null, "ornam", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Pb => new scala.xml.Elem(null, "pb", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Pedal => new scala.xml.Elem(null, "pedal", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.namesdates.PersName => new scala.xml.Elem(null, "persName", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.PgFoot => new scala.xml.Elem(null, "pgFoot", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.PgHead => new scala.xml.Elem(null, "pgHead", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.PubPlace => new scala.xml.Elem(null, "pubPlace", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.header.PubStmt => new scala.xml.Elem(null, "pubStmt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.lyrics.Refrain => new scala.xml.Elem(null, "refrain", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Reh => new scala.xml.Elem(null, "reh", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Rend => new scala.xml.Elem(null, "rend", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.RepeatMark => new scala.xml.Elem(null, "repeatMark", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.RespStmt => new scala.xml.Elem(null, "respStmt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Rest => new scala.xml.Elem(null, "rest", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Sb => new scala.xml.Elem(null, "sb", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Score => new scala.xml.Elem(null, "score", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.ScoreDef => new scala.xml.Elem(null, "scoreDef", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Section => new scala.xml.Elem(null, "section", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Slur => new scala.xml.Elem(null, "slur", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Space => new scala.xml.Elem(null, "space", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Staff => new scala.xml.Elem(null, "staff", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.StaffDef => new scala.xml.Elem(null, "staffDef", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.StaffGrp => new scala.xml.Elem(null, "staffGrp", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.stringtab.String => new scala.xml.Elem(null, "string", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Syl => new scala.xml.Elem(null, "syl", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Symbol => new scala.xml.Elem(null, "symbol", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.stringtab.TabDurSym => new scala.xml.Elem(null, "tabDurSym", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.stringtab.TabGrp => new scala.xml.Elem(null, "tabGrp", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Tempo => new scala.xml.Elem(null, "tempo", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Tie => new scala.xml.Elem(null, "tie", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.shared.Title => new scala.xml.Elem(null, "title", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.header.TitleStmt => new scala.xml.Elem(null, "titleStmt", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmnornaments.Trill => new scala.xml.Elem(null, "trill", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmn.Tuplet => new scala.xml.Elem(null, "tuplet", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.cmnornaments.Turn => new scala.xml.Elem(null, "turn", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.lyrics.Verse => new scala.xml.Elem(null, "verse", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case e: meibasic.mei.lyrics.Volta => new scala.xml.Elem(null, "volta", mkAttributes(e.attributes), scope, true, e.elements.map(el => toXmlWithScope(el, scope))*)
    case _ => throw new IllegalArgumentException(s"Unknown element type: ${element.getClass.getName}")
  }
}
