package meibasic

trait SchemaNode
case object SEmpty extends SchemaNode
case object SText extends SchemaNode
case class SRef(clazz: Class[?]) extends SchemaNode
case class SChoice(nodes: scala.List[SchemaNode]) extends SchemaNode
case class SSeq(nodes: scala.List[SchemaNode]) extends SchemaNode
case class SZeroOrMore(node: SchemaNode) extends SchemaNode
case class SOneOrMore(node: SchemaNode) extends SchemaNode
case class SOptional(node: SchemaNode) extends SchemaNode
case class SMacroRef(lazyNode: () => SchemaNode) extends SchemaNode

object Validator {
  def validate(elements: scala.List[Element], schema: SchemaNode): Boolean = {
    matchSchema(elements, schema).exists(_.isEmpty)
  }
  
  private def matchSchema(elems: scala.List[Element], node: SchemaNode): Option[scala.List[Element]] = node match {
    case SEmpty => Some(elems)
    case SText => 
      if (elems.headOption.exists(_.isInstanceOf[Text])) Some(elems.tail) else None
      
    case SRef(clazz) => 
       elems.headOption.filter(e => clazz.isAssignableFrom(e.getClass)).map(_ => elems.tail)
       
    case SSeq(nodes) => 
       nodes.foldLeft(Option(elems)) { (acc, n) => acc.flatMap(es => matchSchema(es, n)) }
       
    case SChoice(nodes) =>
       nodes.view.map(n => matchSchema(elems, n)).find(_.isDefined).flatten
       
    case SZeroOrMore(child) =>
       var current = elems
       var lastMatch: Option[scala.List[Element]] = Some(current)
       while (lastMatch.isDefined) {
         matchSchema(current, child) match {
           case Some(next) if next != current => 
             current = next
             lastMatch = Some(current)
           case _ => 
             lastMatch = None
         }
       }
       Some(current)
       
    case SOneOrMore(child) =>
       matchSchema(elems, child).flatMap(rest => matchSchema(rest, SZeroOrMore(child)))
       
    case SOptional(child) =>
       matchSchema(elems, child).orElse(Some(elems))
       
    case SMacroRef(lazyNode) =>
       matchSchema(elems, lazyNode())
  }
}

object Schemas {
  lazy val schema_accid: SchemaNode = SEmpty
  lazy val schema_arpeg: SchemaNode = SEmpty
  lazy val schema_arranger: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_artic: SchemaNode = SEmpty
  lazy val schema_att_accid_ges: SchemaNode = SEmpty
  lazy val schema_att_accid_log: SchemaNode = SEmpty
  lazy val schema_att_accid_vis: SchemaNode = SEmpty
  lazy val schema_att_accidental: SchemaNode = SEmpty
  lazy val schema_att_accidental_ges: SchemaNode = SEmpty
  lazy val schema_att_arpeg_log: SchemaNode = SEmpty
  lazy val schema_att_arpeg_vis: SchemaNode = SEmpty
  lazy val schema_att_artic_ges: SchemaNode = SEmpty
  lazy val schema_att_artic_log: SchemaNode = SEmpty
  lazy val schema_att_artic_vis: SchemaNode = SEmpty
  lazy val schema_att_articulation: SchemaNode = SEmpty
  lazy val schema_att_attacking: SchemaNode = SEmpty
  lazy val schema_att_augmentDots: SchemaNode = SEmpty
  lazy val schema_att_bTrem_ges: SchemaNode = SEmpty
  lazy val schema_att_bTrem_log: SchemaNode = SEmpty
  lazy val schema_att_bTrem_vis: SchemaNode = SEmpty
  lazy val schema_att_basic: SchemaNode = SEmpty
  lazy val schema_att_beam_log: SchemaNode = SEmpty
  lazy val schema_att_beam_vis: SchemaNode = SEmpty
  lazy val schema_att_beamSecondary: SchemaNode = SEmpty
  lazy val schema_att_beatRpt_log: SchemaNode = SEmpty
  lazy val schema_att_beatRpt_vis: SchemaNode = SEmpty
  lazy val schema_att_breath_ges: SchemaNode = SEmpty
  lazy val schema_att_breath_log: SchemaNode = SEmpty
  lazy val schema_att_breath_vis: SchemaNode = SEmpty
  lazy val schema_att_caesura_ges: SchemaNode = SEmpty
  lazy val schema_att_caesura_log: SchemaNode = SEmpty
  lazy val schema_att_caesura_vis: SchemaNode = SEmpty
  lazy val schema_att_calendared: SchemaNode = SEmpty
  lazy val schema_att_channelized: SchemaNode = SEmpty
  lazy val schema_att_chord_ges: SchemaNode = SEmpty
  lazy val schema_att_chord_log: SchemaNode = SEmpty
  lazy val schema_att_chord_log_cmn: SchemaNode = SEmpty
  lazy val schema_att_chord_vis: SchemaNode = SEmpty
  lazy val schema_att_chord_vis_cmn: SchemaNode = SEmpty
  lazy val schema_att_chordDef_log: SchemaNode = SEmpty
  lazy val schema_att_chordMember_ges: SchemaNode = SEmpty
  lazy val schema_att_chordMember_log: SchemaNode = SEmpty
  lazy val schema_att_clef_log: SchemaNode = SEmpty
  lazy val schema_att_clef_vis: SchemaNode = SEmpty
  lazy val schema_att_clefShape: SchemaNode = SEmpty
  lazy val schema_att_cleffing_log: SchemaNode = SEmpty
  lazy val schema_att_color: SchemaNode = SEmpty
  lazy val schema_att_common: SchemaNode = SEmpty
  lazy val schema_att_controlEvent: SchemaNode = SEmpty
  lazy val schema_att_course_anl: SchemaNode = SEmpty
  lazy val schema_att_course_ges: SchemaNode = SEmpty
  lazy val schema_att_course_log: SchemaNode = SEmpty
  lazy val schema_att_course_vis: SchemaNode = SEmpty
  lazy val schema_att_cue: SchemaNode = SEmpty
  lazy val schema_att_curvature: SchemaNode = SEmpty
  lazy val schema_att_cutout: SchemaNode = SEmpty
  lazy val schema_att_dataPointing: SchemaNode = SEmpty
  lazy val schema_att_datable: SchemaNode = SEmpty
  lazy val schema_att_dir_log: SchemaNode = SEmpty
  lazy val schema_att_dir_vis: SchemaNode = SEmpty
  lazy val schema_att_duration_additive: SchemaNode = SEmpty
  lazy val schema_att_duration_log: SchemaNode = SEmpty
  lazy val schema_att_duration_ratio: SchemaNode = SEmpty
  lazy val schema_att_dynam_log: SchemaNode = SEmpty
  lazy val schema_att_dynam_vis: SchemaNode = SEmpty
  lazy val schema_att_enclosingChars: SchemaNode = SEmpty
  lazy val schema_att_ending_log: SchemaNode = SEmpty
  lazy val schema_att_ending_vis: SchemaNode = SEmpty
  lazy val schema_att_event: SchemaNode = SEmpty
  lazy val schema_att_expandable: SchemaNode = SEmpty
  lazy val schema_att_extSym: SchemaNode = SEmpty
  lazy val schema_att_extSym_auth: SchemaNode = SEmpty
  lazy val schema_att_extSym_names: SchemaNode = SEmpty
  lazy val schema_att_extender: SchemaNode = SEmpty
  lazy val schema_att_f_ges: SchemaNode = SEmpty
  lazy val schema_att_f_log: SchemaNode = SEmpty
  lazy val schema_att_f_vis: SchemaNode = SEmpty
  lazy val schema_att_fTrem_ges: SchemaNode = SEmpty
  lazy val schema_att_fTrem_log: SchemaNode = SEmpty
  lazy val schema_att_fermata_log: SchemaNode = SEmpty
  lazy val schema_att_fermata_vis: SchemaNode = SEmpty
  lazy val schema_att_fing_ges: SchemaNode = SEmpty
  lazy val schema_att_fing_log: SchemaNode = SEmpty
  lazy val schema_att_fing_vis: SchemaNode = SEmpty
  lazy val schema_att_fingGrp_ges: SchemaNode = SEmpty
  lazy val schema_att_fingGrp_log: SchemaNode = SEmpty
  lazy val schema_att_formework: SchemaNode = SEmpty
  lazy val schema_att_gliss_ges: SchemaNode = SEmpty
  lazy val schema_att_gliss_log: SchemaNode = SEmpty
  lazy val schema_att_gliss_vis: SchemaNode = SEmpty
  lazy val schema_att_graceGrp_log: SchemaNode = SEmpty
  lazy val schema_att_graceGrp_vis: SchemaNode = SEmpty
  lazy val schema_att_graced: SchemaNode = SEmpty
  lazy val schema_att_hairpin_ges: SchemaNode = SEmpty
  lazy val schema_att_hairpin_log: SchemaNode = SEmpty
  lazy val schema_att_hairpin_vis: SchemaNode = SEmpty
  lazy val schema_att_halfmRpt_log: SchemaNode = SEmpty
  lazy val schema_att_halfmRpt_vis: SchemaNode = SEmpty
  lazy val schema_att_harm_log: SchemaNode = SEmpty
  lazy val schema_att_harm_vis: SchemaNode = SEmpty
  lazy val schema_att_harpPedal_ges: SchemaNode = SEmpty
  lazy val schema_att_harpPedal_log: SchemaNode = SEmpty
  lazy val schema_att_harpPedal_vis: SchemaNode = SEmpty
  lazy val schema_att_horizontalAlign: SchemaNode = SEmpty
  lazy val schema_att_id: SchemaNode = SEmpty
  lazy val schema_att_instrDef_ges: SchemaNode = SEmpty
  lazy val schema_att_instrDef_log: SchemaNode = SEmpty
  lazy val schema_att_instrumentIdent: SchemaNode = SEmpty
  lazy val schema_att_keySigDefault_log: SchemaNode = SEmpty
  lazy val schema_att_labelled: SchemaNode = SEmpty
  lazy val schema_att_lang: SchemaNode = SEmpty
  lazy val schema_att_layer_vis: SchemaNode = SEmpty
  lazy val schema_att_layerIdent: SchemaNode = SEmpty
  lazy val schema_att_lineLoc: SchemaNode = SEmpty
  lazy val schema_att_lineRend: SchemaNode = SEmpty
  lazy val schema_att_lineRend_base: SchemaNode = SEmpty
  lazy val schema_att_lv_ges: SchemaNode = SEmpty
  lazy val schema_att_lv_log: SchemaNode = SEmpty
  lazy val schema_att_lv_vis: SchemaNode = SEmpty
  lazy val schema_att_mNum_vis: SchemaNode = SEmpty
  lazy val schema_att_mRest_ges: SchemaNode = SEmpty
  lazy val schema_att_mRest_log: SchemaNode = SEmpty
  lazy val schema_att_mRest_vis: SchemaNode = SEmpty
  lazy val schema_att_mRpt_log: SchemaNode = SEmpty
  lazy val schema_att_mRpt_vis: SchemaNode = SEmpty
  lazy val schema_att_mdiv_ges: SchemaNode = SEmpty
  lazy val schema_att_measure_ges: SchemaNode = SEmpty
  lazy val schema_att_measure_log: SchemaNode = SEmpty
  lazy val schema_att_meiVersion: SchemaNode = SEmpty
  lazy val schema_att_meterConformance_bar: SchemaNode = SEmpty
  lazy val schema_att_meterSigDefault_log: SchemaNode = SEmpty
  lazy val schema_att_midiInstrument: SchemaNode = SEmpty
  lazy val schema_att_midiTempo: SchemaNode = SEmpty
  lazy val schema_att_midiValue: SchemaNode = SEmpty
  lazy val schema_att_midiValue2: SchemaNode = SEmpty
  lazy val schema_att_midiVelocity: SchemaNode = SEmpty
  lazy val schema_att_mmTempo: SchemaNode = SEmpty
  lazy val schema_att_mordent_log: SchemaNode = SEmpty
  lazy val schema_att_mordent_vis: SchemaNode = SEmpty
  lazy val schema_att_multiRest_ges: SchemaNode = SEmpty
  lazy val schema_att_multiRest_log: SchemaNode = SEmpty
  lazy val schema_att_multiRest_vis: SchemaNode = SEmpty
  lazy val schema_att_multiRpt_log: SchemaNode = SEmpty
  lazy val schema_att_multiRpt_vis: SchemaNode = SEmpty
  lazy val schema_att_nInteger: SchemaNode = SEmpty
  lazy val schema_att_nNumberLike: SchemaNode = SEmpty
  lazy val schema_att_name: SchemaNode = SEmpty
  lazy val schema_att_note_ges: SchemaNode = SEmpty
  lazy val schema_att_note_log: SchemaNode = SEmpty
  lazy val schema_att_note_log_cmn: SchemaNode = SEmpty
  lazy val schema_att_note_vis: SchemaNode = SEmpty
  lazy val schema_att_note_vis_cmn: SchemaNode = SEmpty
  lazy val schema_att_numberPlacement: SchemaNode = SEmpty
  lazy val schema_att_numbered: SchemaNode = SEmpty
  lazy val schema_att_octave: SchemaNode = SEmpty
  lazy val schema_att_octave_ges: SchemaNode = SEmpty
  lazy val schema_att_octave_log: SchemaNode = SEmpty
  lazy val schema_att_octave_vis: SchemaNode = SEmpty
  lazy val schema_att_octaveDisplacement: SchemaNode = SEmpty
  lazy val schema_att_ornam_ges: SchemaNode = SEmpty
  lazy val schema_att_ornam_log: SchemaNode = SEmpty
  lazy val schema_att_ornam_vis: SchemaNode = SEmpty
  lazy val schema_att_ornamentAccid: SchemaNode = SEmpty
  lazy val schema_att_ornamentAccid_ges: SchemaNode = SEmpty
  lazy val schema_att_pb_log: SchemaNode = SEmpty
  lazy val schema_att_pb_vis: SchemaNode = SEmpty
  lazy val schema_att_pedal_ges: SchemaNode = SEmpty
  lazy val schema_att_pedal_log: SchemaNode = SEmpty
  lazy val schema_att_pedal_vis: SchemaNode = SEmpty
  lazy val schema_att_pitch: SchemaNode = SEmpty
  lazy val schema_att_pitched: SchemaNode = SEmpty
  lazy val schema_att_placementRelEvent: SchemaNode = SEmpty
  lazy val schema_att_placementRelStaff: SchemaNode = SEmpty
  lazy val schema_att_plist: SchemaNode = SEmpty
  lazy val schema_att_refrain_vis: SchemaNode = SEmpty
  lazy val schema_att_reh_log: SchemaNode = SEmpty
  lazy val schema_att_reh_vis: SchemaNode = SEmpty
  lazy val schema_att_repeatMark_anl: SchemaNode = SEmpty
  lazy val schema_att_repeatMark_ges: SchemaNode = SEmpty
  lazy val schema_att_repeatMark_log: SchemaNode = SEmpty
  lazy val schema_att_repeatMark_vis: SchemaNode = SEmpty
  lazy val schema_att_rest_ges: SchemaNode = SEmpty
  lazy val schema_att_rest_log: SchemaNode = SEmpty
  lazy val schema_att_rest_vis: SchemaNode = SEmpty
  lazy val schema_att_rest_vis_cmn: SchemaNode = SEmpty
  lazy val schema_att_sb_log: SchemaNode = SEmpty
  lazy val schema_att_sb_vis: SchemaNode = SEmpty
  lazy val schema_att_scalable: SchemaNode = SEmpty
  lazy val schema_att_score_ges: SchemaNode = SEmpty
  lazy val schema_att_section_ges: SchemaNode = SEmpty
  lazy val schema_att_section_log: SchemaNode = SEmpty
  lazy val schema_att_section_vis: SchemaNode = SEmpty
  lazy val schema_att_slur_ges: SchemaNode = SEmpty
  lazy val schema_att_slur_log: SchemaNode = SEmpty
  lazy val schema_att_slur_vis: SchemaNode = SEmpty
  lazy val schema_att_soundLocation: SchemaNode = SEmpty
  lazy val schema_att_space_ges: SchemaNode = SEmpty
  lazy val schema_att_space_log: SchemaNode = SEmpty
  lazy val schema_att_space_vis: SchemaNode = SEmpty
  lazy val schema_att_staff_vis: SchemaNode = SEmpty
  lazy val schema_att_staffDef_ges: SchemaNode = SEmpty
  lazy val schema_att_staffDef_log: SchemaNode = SEmpty
  lazy val schema_att_staffDef_log_cmn: SchemaNode = SEmpty
  lazy val schema_att_staffDef_vis: SchemaNode = SEmpty
  lazy val schema_att_staffGroupingSym: SchemaNode = SEmpty
  lazy val schema_att_staffGrp_ges: SchemaNode = SEmpty
  lazy val schema_att_staffGrp_vis: SchemaNode = SEmpty
  lazy val schema_att_staffIdent: SchemaNode = SEmpty
  lazy val schema_att_staffLoc_pitched: SchemaNode = SEmpty
  lazy val schema_att_startEndId: SchemaNode = SEmpty
  lazy val schema_att_startId: SchemaNode = SEmpty
  lazy val schema_att_stems: SchemaNode = SEmpty
  lazy val schema_att_stringtab: SchemaNode = SEmpty
  lazy val schema_att_stringtab_position: SchemaNode = SEmpty
  lazy val schema_att_stringtab_tuning: SchemaNode = SEmpty
  lazy val schema_att_syl_log: SchemaNode = SEmpty
  lazy val schema_att_syl_vis: SchemaNode = SEmpty
  lazy val schema_att_symbol_vis: SchemaNode = SEmpty
  lazy val schema_att_tabDurSym_anl: SchemaNode = SEmpty
  lazy val schema_att_tabDurSym_ges: SchemaNode = SEmpty
  lazy val schema_att_tabDurSym_log: SchemaNode = SEmpty
  lazy val schema_att_tabDurSym_vis: SchemaNode = SEmpty
  lazy val schema_att_tabGrp_anl: SchemaNode = SEmpty
  lazy val schema_att_tabGrp_ges: SchemaNode = SEmpty
  lazy val schema_att_tabGrp_log: SchemaNode = SEmpty
  lazy val schema_att_tabGrp_vis: SchemaNode = SEmpty
  lazy val schema_att_tempo_ges: SchemaNode = SEmpty
  lazy val schema_att_tempo_log: SchemaNode = SEmpty
  lazy val schema_att_tempo_vis: SchemaNode = SEmpty
  lazy val schema_att_textRendition: SchemaNode = SEmpty
  lazy val schema_att_tie_ges: SchemaNode = SEmpty
  lazy val schema_att_tie_log: SchemaNode = SEmpty
  lazy val schema_att_tie_vis: SchemaNode = SEmpty
  lazy val schema_att_timeBase: SchemaNode = SEmpty
  lazy val schema_att_timestamp_log: SchemaNode = SEmpty
  lazy val schema_att_timestamp2_log: SchemaNode = SEmpty
  lazy val schema_att_transposition: SchemaNode = SEmpty
  lazy val schema_att_tremForm: SchemaNode = SEmpty
  lazy val schema_att_tremMeasured: SchemaNode = SEmpty
  lazy val schema_att_trill_ges: SchemaNode = SEmpty
  lazy val schema_att_trill_log: SchemaNode = SEmpty
  lazy val schema_att_trill_vis: SchemaNode = SEmpty
  lazy val schema_att_tuning: SchemaNode = SEmpty
  lazy val schema_att_tuplet_ges: SchemaNode = SEmpty
  lazy val schema_att_tuplet_log: SchemaNode = SEmpty
  lazy val schema_att_tuplet_vis: SchemaNode = SEmpty
  lazy val schema_att_turn_log: SchemaNode = SEmpty
  lazy val schema_att_turn_vis: SchemaNode = SEmpty
  lazy val schema_att_typed: SchemaNode = SEmpty
  lazy val schema_att_typography: SchemaNode = SEmpty
  lazy val schema_att_verse_vis: SchemaNode = SEmpty
  lazy val schema_att_verticalAlign: SchemaNode = SEmpty
  lazy val schema_att_visualOffset: SchemaNode = SEmpty
  lazy val schema_att_visualOffset_ho: SchemaNode = SEmpty
  lazy val schema_att_visualOffset_vo: SchemaNode = SEmpty
  lazy val schema_att_visualOffset2: SchemaNode = SEmpty
  lazy val schema_att_visualOffset2_ho: SchemaNode = SEmpty
  lazy val schema_att_visualOffset2_vo: SchemaNode = SEmpty
  lazy val schema_att_volta_vis: SchemaNode = SEmpty
  lazy val schema_att_voltaGroupingSym: SchemaNode = SEmpty
  lazy val schema_att_whitespace: SchemaNode = SEmpty
  lazy val schema_att_width: SchemaNode = SEmpty
  lazy val schema_availability: SchemaNode = SRef(classOf[meibasic.mei.header.macro_.AvailabilityPart])
  lazy val schema_bTrem: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Chord]), SRef(classOf[meibasic.mei.shared.Note])))
  lazy val schema_barre: SchemaNode = SEmpty
  lazy val schema_beam: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.EventLike]), SRef(classOf[meibasic.mei.cmn.model.eventlike.Cmn]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_beatRpt: SchemaNode = SEmpty
  lazy val schema_body: SchemaNode = SOneOrMore(SChoice(scala.List(SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.MdivLike]))))
  lazy val schema_breath: SchemaNode = SEmpty
  lazy val schema_caesura: SchemaNode = SEmpty
  lazy val schema_chord: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.ChordPart]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.SylLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.lyrics.model.VerseLike]))))
  lazy val schema_chordDef: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.harmony.ChordMember])), SZeroOrMore(SRef(classOf[meibasic.mei.stringtab.Barre]))))
  lazy val schema_chordMember: SchemaNode = SEmpty
  lazy val schema_chordTable: SchemaNode = SOneOrMore(SRef(classOf[meibasic.mei.harmony.ChordDef]))
  lazy val schema_clef: SchemaNode = SEmpty
  lazy val schema_clefGrp: SchemaNode = SOneOrMore(SRef(classOf[meibasic.mei.shared.Clef]))
  lazy val schema_composer: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_course: SchemaNode = SZeroOrMore(SRef(classOf[meibasic.mei.stringtab.String]))
  lazy val schema_data_ACCIDENTAL_GESTURAL: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_GESTURAL_basic: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_GESTURAL_extended: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_WRITTEN: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_WRITTEN_basic: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_WRITTEN_extended: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_aeu: SchemaNode = SText
  lazy val schema_data_ACCIDENTAL_persian: SchemaNode = SText
  lazy val schema_data_ARTICULATION: SchemaNode = SText
  lazy val schema_data_AUGMENTDOT: SchemaNode = SText
  lazy val schema_data_BARRENDITION: SchemaNode = SText
  lazy val schema_data_BEAT: SchemaNode = SText
  lazy val schema_data_BEATRPT_REND: SchemaNode = SChoice(scala.List(SText, SText))
  lazy val schema_data_BEND_AMOUNT: SchemaNode = SChoice(scala.List(SText, SText, SText))
  lazy val schema_data_BETYPE: SchemaNode = SText
  lazy val schema_data_BOOLEAN: SchemaNode = SText
  lazy val schema_data_CANCELACCID: SchemaNode = SText
  lazy val schema_data_CLEFLINE: SchemaNode = SText
  lazy val schema_data_CLEFSHAPE: SchemaNode = SText
  lazy val schema_data_CLUSTER: SchemaNode = SText
  lazy val schema_data_COLOR: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.COLORNAMES]), SRef(classOf[meibasic.mei.data.COLORVALUES])))
  lazy val schema_data_COLORNAMES: SchemaNode = SText
  lazy val schema_data_COLORVALUES: SchemaNode = SChoice(scala.List(SText, SText, SText, SText, SText, SText))
  lazy val schema_data_COMPASSDIRECTION: SchemaNode = SText
  lazy val schema_data_COMPASSDIRECTION_basic: SchemaNode = SText
  lazy val schema_data_COMPASSDIRECTION_extended: SchemaNode = SText
  lazy val schema_data_CONFIDENCE: SchemaNode = SText
  lazy val schema_data_COURSENUMBER: SchemaNode = SText
  lazy val schema_data_COURSETUNING: SchemaNode = SText
  lazy val schema_data_DEGREES: SchemaNode = SText
  lazy val schema_data_DURATION: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.cmn.data.duration.Cmn]), SRef(classOf[meibasic.Element])))
  lazy val schema_data_DURATION_cmn: SchemaNode = SText
  lazy val schema_data_DURATIONRESTS: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.cmn.data.duration.Cmn]), SRef(classOf[meibasic.Element])))
  lazy val schema_data_ENCLOSURE: SchemaNode = SText
  lazy val schema_data_EVENTREL: SchemaNode = SText
  lazy val schema_data_EVENTREL_basic: SchemaNode = SText
  lazy val schema_data_EVENTREL_extended: SchemaNode = SText
  lazy val schema_data_FINGER_FRET: SchemaNode = SChoice(scala.List(SText, SText))
  lazy val schema_data_FONTFAMILY: SchemaNode = SText
  lazy val schema_data_FONTNAME: SchemaNode = SText
  lazy val schema_data_FONTSIZE: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.FONTSIZENUMERIC]), SRef(classOf[meibasic.mei.data.FONTSIZETERM]), SRef(classOf[meibasic.mei.data.PERCENT])))
  lazy val schema_data_FONTSIZENUMERIC: SchemaNode = SText
  lazy val schema_data_FONTSIZESCALE: SchemaNode = SText
  lazy val schema_data_FONTSIZETERM: SchemaNode = SText
  lazy val schema_data_FONTSTYLE: SchemaNode = SText
  lazy val schema_data_FONTWEIGHT: SchemaNode = SText
  lazy val schema_data_FRETNUMBER: SchemaNode = SText
  lazy val schema_data_GLISSANDO: SchemaNode = SText
  lazy val schema_data_GRACE: SchemaNode = SText
  lazy val schema_data_HARPPEDALPOSITION: SchemaNode = SText
  lazy val schema_data_HEADSHAPE_list: SchemaNode = SText
  lazy val schema_data_HEXNUM: SchemaNode = SText
  lazy val schema_data_HORIZONTALALIGNMENT: SchemaNode = SText
  lazy val schema_data_ISODATE: SchemaNode = SChoice(scala.List(SText, SText, SText, SText, SText, SText, SText, SText, SText))
  lazy val schema_data_KEYFIFTHS: SchemaNode = SText
  lazy val schema_data_LIGATUREFORM: SchemaNode = SText
  lazy val schema_data_LINEFORM: SchemaNode = SText
  lazy val schema_data_LINESTARTENDSYMBOL: SchemaNode = SText
  lazy val schema_data_LINEWIDTH: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.LINEWIDTHTERM]), SRef(classOf[meibasic.mei.data.MEASUREMENTUNSIGNED])))
  lazy val schema_data_LINEWIDTHTERM: SchemaNode = SText
  lazy val schema_data_MEASUREBEAT: SchemaNode = SText
  lazy val schema_data_MEASUREBEATOFFSET: SchemaNode = SText
  lazy val schema_data_MEASUREMENTFONTSIGNED: SchemaNode = SText
  lazy val schema_data_MEASUREMENTFONTUNSIGNED: SchemaNode = SText
  lazy val schema_data_MEASUREMENTSIGNED: SchemaNode = SText
  lazy val schema_data_MEASUREMENTTYPOGRAPHYSIGNED: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.MEASUREMENTFONTSIGNED]), SRef(classOf[meibasic.mei.data.MEASUREMENTSIGNED])))
  lazy val schema_data_MEASUREMENTTYPOGRAPHYUNSIGNED: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.MEASUREMENTFONTUNSIGNED]), SRef(classOf[meibasic.mei.data.MEASUREMENTUNSIGNED])))
  lazy val schema_data_MEASUREMENTUNSIGNED: SchemaNode = SText
  lazy val schema_data_MENSURATIONSIGN: SchemaNode = SText
  lazy val schema_data_METERFORM: SchemaNode = SText
  lazy val schema_data_METERSIGN: SchemaNode = SText
  lazy val schema_data_MIDIBPM: SchemaNode = SText
  lazy val schema_data_MIDICHANNEL: SchemaNode = SText
  lazy val schema_data_MIDIMSPB: SchemaNode = SText
  lazy val schema_data_MIDINAMES: SchemaNode = SText
  lazy val schema_data_MIDIVALUE: SchemaNode = SText
  lazy val schema_data_MIDIVALUE_NAME: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.MIDIVALUE]), SRef(classOf[meibasic.mei.data.NCNAME])))
  lazy val schema_data_MIDIVALUE_PAN: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.MIDIVALUE]), SRef(classOf[meibasic.mei.data.percent.limited.SIGNED])))
  lazy val schema_data_MIDIVALUE_PERCENT: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.MIDIVALUE]), SRef(classOf[meibasic.mei.data.percent.LIMITED])))
  lazy val schema_data_MODE: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.mode.Cmn]), SRef(classOf[meibasic.mei.data.mode.Gregorian]), SRef(classOf[meibasic.mei.data.mode.Extended])))
  lazy val schema_data_MODE_cmn: SchemaNode = SText
  lazy val schema_data_MODE_extended: SchemaNode = SText
  lazy val schema_data_MODE_gregorian: SchemaNode = SText
  lazy val schema_data_MODSRELATIONSHIP: SchemaNode = SText
  lazy val schema_data_NCNAME: SchemaNode = SText
  lazy val schema_data_NEIGHBORINGLAYER: SchemaNode = SText
  lazy val schema_data_NMTOKEN: SchemaNode = SText
  lazy val schema_data_NONSTAFFPLACE: SchemaNode = SText
  lazy val schema_data_NOTEHEADMODIFIER_list: SchemaNode = SText
  lazy val schema_data_NOTEHEADMODIFIER_pat: SchemaNode = SChoice(scala.List(SText, SText))
  lazy val schema_data_OCTAVE: SchemaNode = SText
  lazy val schema_data_OCTAVE_DIS: SchemaNode = SText
  lazy val schema_data_ORIENTATION: SchemaNode = SText
  lazy val schema_data_ORNAM_cmn: SchemaNode = SText
  lazy val schema_data_PEDALSTYLE: SchemaNode = SText
  lazy val schema_data_PERCENT: SchemaNode = SText
  lazy val schema_data_PERCENT_LIMITED: SchemaNode = SText
  lazy val schema_data_PERCENT_LIMITED_SIGNED: SchemaNode = SText
  lazy val schema_data_PGFUNC: SchemaNode = SText
  lazy val schema_data_PITCHNAME: SchemaNode = SText
  lazy val schema_data_PITCHNAME_GESTURAL: SchemaNode = SText
  lazy val schema_data_PITCHNUMBER: SchemaNode = SText
  lazy val schema_data_PLACEMENT: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.STAFFREL]), SRef(classOf[meibasic.mei.data.NONSTAFFPLACE]), SRef(classOf[meibasic.mei.data.NMTOKEN])))
  lazy val schema_data_ROTATIONDIRECTION: SchemaNode = SText
  lazy val schema_data_SLASH: SchemaNode = SText
  lazy val schema_data_SLUR: SchemaNode = SText
  lazy val schema_data_STAFFITEM_basic: SchemaNode = SText
  lazy val schema_data_STAFFITEM_cmn: SchemaNode = SText
  lazy val schema_data_STAFFLOC: SchemaNode = SText
  lazy val schema_data_STAFFREL: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.staffrel.Basic]), SRef(classOf[meibasic.mei.data.staffrel.Extended])))
  lazy val schema_data_STAFFREL_basic: SchemaNode = SText
  lazy val schema_data_STAFFREL_extended: SchemaNode = SText
  lazy val schema_data_STEMDIRECTION: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.stemdirection.Basic]), SRef(classOf[meibasic.mei.data.stemdirection.Extended])))
  lazy val schema_data_STEMDIRECTION_basic: SchemaNode = SText
  lazy val schema_data_STEMDIRECTION_extended: SchemaNode = SText
  lazy val schema_data_STEMMODIFIER: SchemaNode = SText
  lazy val schema_data_STEMPOSITION: SchemaNode = SText
  lazy val schema_data_STRINGNUMBER: SchemaNode = SText
  lazy val schema_data_TEMPERAMENT: SchemaNode = SText
  lazy val schema_data_TEMPOVALUE: SchemaNode = SText
  lazy val schema_data_TEXTRENDITION: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.data.TEXTRENDITIONLIST]), SRef(classOf[meibasic.mei.data.TEXTRENDITIONPAR])))
  lazy val schema_data_TEXTRENDITIONLIST: SchemaNode = SText
  lazy val schema_data_TEXTRENDITIONPAR: SchemaNode = SText
  lazy val schema_data_URI: SchemaNode = SText
  lazy val schema_data_VERTICALALIGNMENT: SchemaNode = SText
  lazy val schema_data_WORD: SchemaNode = SText
  lazy val schema_date: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.TextPhraseLike]))))
  lazy val schema_dir: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_dynam: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_ending: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.Element])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.mei.shared.model.RelationLike]), SRef(classOf[meibasic.mei.shared.model.ScoreDefLike]), SRef(classOf[meibasic.mei.shared.model.SectionLike]), SRef(classOf[meibasic.mei.cmn.model.sectionpart.Cmn]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.StaffDefLike]), SRef(classOf[meibasic.Element]))))))
  lazy val schema_f: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_fTrem: SchemaNode = SChoice(scala.List(SSeq(scala.List(SRef(classOf[meibasic.mei.shared.Chord]), SOptional(SRef(classOf[meibasic.mei.shared.Clef])), SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Chord]), SRef(classOf[meibasic.mei.shared.Note]))))), SSeq(scala.List(SRef(classOf[meibasic.mei.shared.Note]), SOptional(SRef(classOf[meibasic.mei.shared.Clef])), SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Chord]), SRef(classOf[meibasic.mei.shared.Note])))))))
  lazy val schema_fb: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.harmony.model.FLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_fermata: SchemaNode = SEmpty
  lazy val schema_fileDesc: SchemaNode = SSeq(scala.List(SRef(classOf[meibasic.mei.header.TitleStmt]), SRef(classOf[meibasic.mei.header.PubStmt])))
  lazy val schema_fing: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_fingGrp: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.fingering.model.FingeringLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_gliss: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_graceGrp: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.EventLike]), SRef(classOf[meibasic.mei.cmn.model.eventlike.Cmn]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_hairpin: SchemaNode = SEmpty
  lazy val schema_halfmRpt: SchemaNode = SEmpty
  lazy val schema_harm: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.harmony.model.FigbassLike]))))
  lazy val schema_harpPedal: SchemaNode = SEmpty
  lazy val schema_instrDef: SchemaNode = SEmpty
  lazy val schema_label: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_labelAbbr: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_layer: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.LayerPart]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_lb: SchemaNode = SEmpty
  lazy val schema_lv: SchemaNode = SZeroOrMore(SRef(classOf[meibasic.Element]))
  lazy val schema_lyricist: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_mNum: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.LbLike]), SRef(classOf[meibasic.mei.shared.model.RendLike]))))
  lazy val schema_mRest: SchemaNode = SEmpty
  lazy val schema_mRpt: SchemaNode = SEmpty
  lazy val schema_macro_availabilityPart: SchemaNode = SChoice(scala.List(SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.HeadLike])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.AddressLike]), SRef(classOf[meibasic.mei.shared.model.DateLike]), SRef(classOf[meibasic.mei.shared.model.IdentifierLike])))))), SText))
  lazy val schema_macro_metaLike_page: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.mei.shared.PgHead])), SOptional(SRef(classOf[meibasic.mei.shared.PgFoot])), SOptional(SRef(classOf[meibasic.Element]))))
  lazy val schema_macro_musicPart: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.Element])), SOptional(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Body]), SRef(classOf[meibasic.Element])))), SOptional(SRef(classOf[meibasic.Element]))))
  lazy val schema_macro_titlePart: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AddressLike]), SRef(classOf[meibasic.mei.namesdates.model.AddressPart]), SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.mei.shared.model.BiblLike]), SRef(classOf[meibasic.mei.shared.model.DateLike]), SRef(classOf[meibasic.mei.shared.model.EditorialLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.IdentifierLike]), SRef(classOf[meibasic.mei.shared.model.LbLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.MeasurementLike]), SRef(classOf[meibasic.mei.shared.model.NameLike]), SRef(classOf[meibasic.mei.namesdates.model.namelike.Label]), SRef(classOf[meibasic.mei.shared.model.PbLike]), SRef(classOf[meibasic.mei.shared.model.RendLike]), SRef(classOf[meibasic.mei.shared.Symbol]))))
  lazy val schema_mdiv: SchemaNode = SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.ScoreLike]), SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.MdivLike]))))
  lazy val schema_measure: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.mei.cmn.MNum])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.cmn.model.MeasurePart]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.mei.shared.model.RelationLike]), SRef(classOf[meibasic.Element]))))))
  lazy val schema_mei: SchemaNode = SSeq(scala.List(SRef(classOf[meibasic.mei.header.MeiHead]), SRef(classOf[meibasic.mei.shared.Music])))
  lazy val schema_meiHead: SchemaNode = SRef(classOf[meibasic.mei.header.FileDesc])
  lazy val schema_model_addressLike: SchemaNode = SEmpty
  lazy val schema_model_addressPart: SchemaNode = SEmpty
  lazy val schema_model_annotLike: SchemaNode = SEmpty
  lazy val schema_model_biblLike: SchemaNode = SEmpty
  lazy val schema_model_chordPart: SchemaNode = SEmpty
  lazy val schema_model_controlEventLike: SchemaNode = SEmpty
  lazy val schema_model_controlEventLike_cmn: SchemaNode = SEmpty
  lazy val schema_model_controlEventLike_harmony: SchemaNode = SEmpty
  lazy val schema_model_dateLike: SchemaNode = SEmpty
  lazy val schema_model_dimLike: SchemaNode = SEmpty
  lazy val schema_model_editorialLike: SchemaNode = SEmpty
  lazy val schema_model_endingLike: SchemaNode = SEmpty
  lazy val schema_model_eventLike: SchemaNode = SEmpty
  lazy val schema_model_eventLike_cmn: SchemaNode = SEmpty
  lazy val schema_model_eventLike_measureFilling: SchemaNode = SEmpty
  lazy val schema_model_fLike: SchemaNode = SEmpty
  lazy val schema_model_figbassLike: SchemaNode = SEmpty
  lazy val schema_model_fingeringLike: SchemaNode = SEmpty
  lazy val schema_model_geogNamePart: SchemaNode = SEmpty
  lazy val schema_model_harmLike: SchemaNode = SEmpty
  lazy val schema_model_headLike: SchemaNode = SEmpty
  lazy val schema_model_identifierLike: SchemaNode = SEmpty
  lazy val schema_model_instrDefLike: SchemaNode = SEmpty
  lazy val schema_model_keySigLike: SchemaNode = SEmpty
  lazy val schema_model_labelLike: SchemaNode = SEmpty
  lazy val schema_model_layerDefLike: SchemaNode = SEmpty
  lazy val schema_model_layerLike: SchemaNode = SEmpty
  lazy val schema_model_layerPart: SchemaNode = SEmpty
  lazy val schema_model_layerPart_cmn: SchemaNode = SEmpty
  lazy val schema_model_lbLike: SchemaNode = SEmpty
  lazy val schema_model_mdivLike: SchemaNode = SEmpty
  lazy val schema_model_measureLike: SchemaNode = SEmpty
  lazy val schema_model_measurePart: SchemaNode = SEmpty
  lazy val schema_model_measurementLike: SchemaNode = SEmpty
  lazy val schema_model_meterSigLike: SchemaNode = SEmpty
  lazy val schema_model_midiLike: SchemaNode = SEmpty
  lazy val schema_model_milestoneLike_music: SchemaNode = SEmpty
  lazy val schema_model_nameLike: SchemaNode = SEmpty
  lazy val schema_model_nameLike_agent: SchemaNode = SEmpty
  lazy val schema_model_nameLike_geogName: SchemaNode = SEmpty
  lazy val schema_model_nameLike_label: SchemaNode = SEmpty
  lazy val schema_model_nameLike_place: SchemaNode = SEmpty
  lazy val schema_model_noteModifierLike: SchemaNode = SEmpty
  lazy val schema_model_numLike: SchemaNode = SEmpty
  lazy val schema_model_ornamentLike_cmn: SchemaNode = SEmpty
  lazy val schema_model_ossiaLike: SchemaNode = SEmpty
  lazy val schema_model_pLike: SchemaNode = SEmpty
  lazy val schema_model_pbLike: SchemaNode = SEmpty
  lazy val schema_model_persNamePart: SchemaNode = SEmpty
  lazy val schema_model_relationLike: SchemaNode = SEmpty
  lazy val schema_model_rendLike: SchemaNode = SEmpty
  lazy val schema_model_repositoryLike: SchemaNode = SEmpty
  lazy val schema_model_resourceLike: SchemaNode = SEmpty
  lazy val schema_model_respLike: SchemaNode = SEmpty
  lazy val schema_model_respLikePart: SchemaNode = SEmpty
  lazy val schema_model_scoreDefLike: SchemaNode = SEmpty
  lazy val schema_model_scoreLike: SchemaNode = SEmpty
  lazy val schema_model_scorePart: SchemaNode = SEmpty
  lazy val schema_model_sectionLike: SchemaNode = SEmpty
  lazy val schema_model_sectionPart: SchemaNode = SEmpty
  lazy val schema_model_sectionPart_cmn: SchemaNode = SEmpty
  lazy val schema_model_staffDefLike: SchemaNode = SEmpty
  lazy val schema_model_staffDefPart: SchemaNode = SEmpty
  lazy val schema_model_staffGrpLike: SchemaNode = SEmpty
  lazy val schema_model_staffLike: SchemaNode = SEmpty
  lazy val schema_model_staffPart: SchemaNode = SEmpty
  lazy val schema_model_sylLike: SchemaNode = SEmpty
  lazy val schema_model_textComponentLike: SchemaNode = SEmpty
  lazy val schema_model_textPhraseLike: SchemaNode = SEmpty
  lazy val schema_model_textPhraseLike_limited: SchemaNode = SEmpty
  lazy val schema_model_titleLike: SchemaNode = SEmpty
  lazy val schema_model_verseLike: SchemaNode = SEmpty
  lazy val schema_mordent: SchemaNode = SEmpty
  lazy val schema_multiRest: SchemaNode = SEmpty
  lazy val schema_multiRpt: SchemaNode = SEmpty
  lazy val schema_music: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.ResourceLike])), SRef(classOf[meibasic.mei.shared.macro_.MusicPart])))
  lazy val schema_note: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.NoteModifierLike]), SRef(classOf[meibasic.mei.lyrics.model.VerseLike]), SRef(classOf[meibasic.mei.shared.model.SylLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_octave: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_ornam: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_pb: SchemaNode = SRef(classOf[meibasic.mei.shared.macro_.metalike.Page])
  lazy val schema_pedal: SchemaNode = SEmpty
  lazy val schema_persName: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.TextPhraseLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.namesdates.model.PersNamePart]))))
  lazy val schema_pgFoot: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.TextComponentLike]), SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_pgHead: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.TextComponentLike]), SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_pubPlace: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]))))
  lazy val schema_pubStmt: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.Element])), SOptional(SRef(classOf[meibasic.mei.shared.PubPlace])), SOptional(SRef(classOf[meibasic.mei.shared.Date])), SOptional(SRef(classOf[meibasic.mei.header.Availability]))))
  lazy val schema_refrain: SchemaNode = SSeq(scala.List(SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Dir]), SRef(classOf[meibasic.mei.shared.Dynam]), SRef(classOf[meibasic.mei.shared.Tempo]), SRef(classOf[meibasic.mei.shared.Space])))), SOneOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.lyrics.Volta]), SRef(classOf[meibasic.mei.shared.model.SylLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element])))), SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.LbLike]))))
  lazy val schema_reh: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.LbLike]), SRef(classOf[meibasic.mei.shared.model.RendLike]))))
  lazy val schema_rend: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.TextPhraseLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_repeatMark: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_respStmt: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.HeadLike])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.namesdates.model.namelike.Agent]))))))
  lazy val schema_rest: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_sb: SchemaNode = SEmpty
  lazy val schema_score: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.mei.shared.model.RelationLike]), SRef(classOf[meibasic.mei.shared.model.ScoreDefLike]), SRef(classOf[meibasic.mei.shared.model.ScorePart]), SRef(classOf[meibasic.mei.shared.model.StaffDefLike]), SRef(classOf[meibasic.Element]))))
  lazy val schema_scoreDef: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.Element])), SOptional(SRef(classOf[meibasic.mei.shared.model.KeySigLike])), SOptional(SRef(classOf[meibasic.mei.shared.model.MeterSigLike])), SOptional(SRef(classOf[meibasic.mei.shared.PgHead])), SOptional(SRef(classOf[meibasic.mei.shared.PgFoot])), SOptional(SRef(classOf[meibasic.Element])), SChoice(scala.List(SOptional(SRef(classOf[meibasic.mei.shared.model.StaffGrpLike]))))))
  lazy val schema_section: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.Element])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.mei.shared.model.RelationLike]), SRef(classOf[meibasic.mei.shared.model.SectionPart]), SRef(classOf[meibasic.Element]))))))
  lazy val schema_slur: SchemaNode = SZeroOrMore(SRef(classOf[meibasic.Element]))
  lazy val schema_space: SchemaNode = SEmpty
  lazy val schema_staff: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.AnnotLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.milestonelike.Music]), SRef(classOf[meibasic.mei.shared.model.RelationLike]), SRef(classOf[meibasic.mei.shared.model.StaffDefLike]), SRef(classOf[meibasic.mei.shared.model.StaffPart]), SRef(classOf[meibasic.Element]))))
  lazy val schema_staffDef: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.LabelLike])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.InstrDefLike]), SRef(classOf[meibasic.mei.shared.model.LayerDefLike]), SRef(classOf[meibasic.mei.shared.model.StaffDefPart])))), SOptional(SRef(classOf[meibasic.Element]))))
  lazy val schema_staffGrp: SchemaNode = SSeq(scala.List(SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.LabelLike])))), SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.InstrDefLike])), SOneOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.StaffGrpLike]), SRef(classOf[meibasic.mei.shared.model.StaffDefLike]))))))
  lazy val schema_string: SchemaNode = SZeroOrMore(SRef(classOf[meibasic.mei.stringtab.String]))
  lazy val schema_syl: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_symbol: SchemaNode = SEmpty
  lazy val schema_tabDurSym: SchemaNode = SEmpty
  lazy val schema_tabGrp: SchemaNode = SSeq(scala.List(SOptional(SRef(classOf[meibasic.mei.stringtab.TabDurSym])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Note]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.Rest]))))))
  lazy val schema_tempo: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.model.textphraselike.Limited]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_tie: SchemaNode = SZeroOrMore(SRef(classOf[meibasic.Element]))
  lazy val schema_title: SchemaNode = SZeroOrMore(SChoice(scala.List(SText, SRef(classOf[meibasic.mei.shared.macro_.TitlePart]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]))))
  lazy val schema_titleStmt: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.HeadLike])), SOneOrMore(SRef(classOf[meibasic.mei.shared.model.TitleLike])), SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.RespLike]))))))
  lazy val schema_trill: SchemaNode = SEmpty
  lazy val schema_tuplet: SchemaNode = SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.mei.shared.model.EventLike]), SRef(classOf[meibasic.mei.cmn.model.eventlike.Cmn]), SRef(classOf[meibasic.Element]))))
  lazy val schema_turn: SchemaNode = SEmpty
  lazy val schema_verse: SchemaNode = SSeq(scala.List(SZeroOrMore(SRef(classOf[meibasic.mei.shared.Label])), SZeroOrMore(SRef(classOf[meibasic.mei.shared.LabelAbbr])), SOneOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.lyrics.Volta]), SRef(classOf[meibasic.mei.shared.model.SylLike]))))))
  lazy val schema_volta: SchemaNode = SSeq(scala.List(SZeroOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.Dir]), SRef(classOf[meibasic.mei.shared.Dynam]), SRef(classOf[meibasic.mei.shared.Tempo]), SRef(classOf[meibasic.mei.shared.Space])))), SOneOrMore(SChoice(scala.List(SRef(classOf[meibasic.mei.shared.model.SylLike]), SRef(classOf[meibasic.Element]), SRef(classOf[meibasic.Element])))), SZeroOrMore(SRef(classOf[meibasic.mei.shared.model.LbLike]))))
}
