package meibasic

import scala.language.implicitConversions

object Syntax {
  implicit def stringToElement(s: java.lang.String): Element = Text(s)

  def accid(`accid`: java.lang.String = null, `accid.ges`: java.lang.String = null, `color`: java.lang.String = null, `enclose`: java.lang.String = null, `func`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Accid = 
    meibasic.mei.shared.Accid.apply(`accid`, `accid.ges`, `color`, `enclose`, `func`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `plist`, `staff`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def arpeg(`arrow`: java.lang.String = null, `arrow.color`: java.lang.String = null, `arrow.fillcolor`: java.lang.String = null, `arrow.shape`: java.lang.String = null, `arrow.size`: java.lang.String = null, `color`: java.lang.String = null, `enclose`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lform`: java.lang.String = null, `lineheight`: java.lang.String = null, `lsegs`: java.lang.String = null, `lwidth`: java.lang.String = null, `order`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Arpeg = 
    meibasic.mei.cmn.Arpeg.apply(`arrow`, `arrow.color`, `arrow.fillcolor`, `arrow.shape`, `arrow.size`, `color`, `enclose`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lform`, `lineheight`, `lsegs`, `lwidth`, `order`, `plist`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def arranger(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Arranger = 
    meibasic.mei.shared.Arranger.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def artic(`artic`: java.lang.String = null, `color`: java.lang.String = null, `enclose`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Artic = 
    meibasic.mei.shared.Artic.apply(`artic`, `color`, `enclose`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `place`, `plist`, `staff`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def availability(`data`: java.lang.String = null, `label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.header.Availability = 
    meibasic.mei.header.Availability.apply(`data`, `label`, `type`, `xml:id`)(elements*)

  def bTrem(`dots`: java.lang.String = null, `dur`: java.lang.String = null, `form`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `num`: java.lang.String = null, `num.place`: java.lang.String = null, `num.visible`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `unitdur`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.BTrem = 
    meibasic.mei.cmn.BTrem.apply(`dots`, `dur`, `form`, `label`, `layer`, `num`, `num.place`, `num.visible`, `staff`, `type`, `unitdur`, `xml:id`)(elements*)

  def barre(`endid`: java.lang.String = null, `fret`: java.lang.String = null, `label`: java.lang.String = null, `startid`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.stringtab.Barre = 
    meibasic.mei.stringtab.Barre.apply(`endid`, `fret`, `label`, `startid`, `type`, `xml:id`)(elements*)

  def beam(`color`: java.lang.String = null, `cue`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Beam = 
    meibasic.mei.cmn.Beam.apply(`color`, `cue`, `label`, `layer`, `staff`, `type`, `xml:id`)(elements*)

  def beatRpt(`beatdef`: java.lang.String = null, `color`: java.lang.String = null, `expand`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `plist`: java.lang.String = null, `slash`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.BeatRpt = 
    meibasic.mei.cmn.BeatRpt.apply(`beatdef`, `color`, `expand`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `label`, `layer`, `plist`, `slash`, `staff`, `type`, `xml:id`)(elements*)

  def body(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Body = 
    meibasic.mei.shared.Body.apply(`label`, `type`, `xml:id`)(elements*)

  def breath(`color`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Breath = 
    meibasic.mei.cmn.Breath.apply(`color`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def caesura(`color`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Caesura = 
    meibasic.mei.shared.Caesura.apply(`color`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def chord(`breaksec`: java.lang.String = null, `cluster`: java.lang.String = null, `color`: java.lang.String = null, `cue`: java.lang.String = null, `dots`: java.lang.String = null, `dur`: java.lang.String = null, `enclose`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `grace`: java.lang.String = null, `grace.time`: java.lang.String = null, `ho`: java.lang.String = null, `instr`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `stem.dir`: java.lang.String = null, `stem.len`: java.lang.String = null, `stem.mod`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Chord = 
    meibasic.mei.shared.Chord.apply(`breaksec`, `cluster`, `color`, `cue`, `dots`, `dur`, `enclose`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `grace`, `grace.time`, `ho`, `instr`, `label`, `layer`, `staff`, `stem.dir`, `stem.len`, `stem.mod`, `type`, `xml:id`)(elements*)

  def chordDef(`label`: java.lang.String = null, `tab.courses`: java.lang.String = null, `tab.pos`: java.lang.String = null, `tab.strings`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.ChordDef = 
    meibasic.mei.harmony.ChordDef.apply(`label`, `tab.courses`, `tab.pos`, `tab.strings`, `type`, `xml:id`)(elements*)

  def chordMember(`accid.ges`: java.lang.String = null, `label`: java.lang.String = null, `oct`: java.lang.String = null, `pname`: java.lang.String = null, `tab.course`: java.lang.String = null, `tab.fing`: java.lang.String = null, `tab.fret`: java.lang.String = null, `tab.line`: java.lang.String = null, `tab.string`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.ChordMember = 
    meibasic.mei.harmony.ChordMember.apply(`accid.ges`, `label`, `oct`, `pname`, `tab.course`, `tab.fing`, `tab.fret`, `tab.line`, `tab.string`, `type`, `xml:id`)(elements*)

  def chordTable(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.ChordTable = 
    meibasic.mei.harmony.ChordTable.apply(`label`, `type`, `xml:id`)(elements*)

  def clef(`cautionary`: java.lang.String = null, `color`: java.lang.String = null, `dis`: java.lang.String = null, `dis.place`: java.lang.String = null, `enclose`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `line`: java.lang.String = null, `lineheight`: java.lang.String = null, `oct`: java.lang.String = null, `shape`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Clef = 
    meibasic.mei.shared.Clef.apply(`cautionary`, `color`, `dis`, `dis.place`, `enclose`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `line`, `lineheight`, `oct`, `shape`, `staff`, `type`, `vo`, `xml:id`)(elements*)

  def clefGrp(`label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.ClefGrp = 
    meibasic.mei.shared.ClefGrp.apply(`label`, `layer`, `staff`, `type`, `xml:id`)(elements*)

  def composer(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Composer = 
    meibasic.mei.shared.Composer.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def course(`accid`: java.lang.String = null, `label`: java.lang.String = null, `oct`: java.lang.String = null, `pname`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.stringtab.Course = 
    meibasic.mei.stringtab.Course.apply(`accid`, `label`, `oct`, `pname`, `type`, `xml:id`)(elements*)

  def date(`calendar`: java.lang.String = null, `enddate`: java.lang.String = null, `isodate`: java.lang.String = null, `label`: java.lang.String = null, `notafter`: java.lang.String = null, `notbefore`: java.lang.String = null, `startdate`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Date = 
    meibasic.mei.shared.Date.apply(`calendar`, `enddate`, `isodate`, `label`, `notafter`, `notbefore`, `startdate`, `type`, `xml:id`, `xml:lang`)(elements*)

  def dir(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Dir = 
    meibasic.mei.shared.Dir.apply(`color`, `dur`, `endho`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def dynam(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Dynam = 
    meibasic.mei.shared.Dynam.apply(`color`, `dur`, `endho`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def ending(`label`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Ending = 
    meibasic.mei.shared.Ending.apply(`label`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `type`, `xml:id`)(elements*)

  def f(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.F = 
    meibasic.mei.harmony.F.apply(`color`, `dur`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def fTrem(`dots`: java.lang.String = null, `dur`: java.lang.String = null, `form`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `unitdur`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.FTrem = 
    meibasic.mei.cmn.FTrem.apply(`dots`, `dur`, `form`, `label`, `layer`, `staff`, `type`, `unitdur`, `xml:id`)(elements*)

  def fb(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.Fb = 
    meibasic.mei.harmony.Fb.apply(`label`, `type`, `xml:id`)(elements*)

  def fermata(`color`: java.lang.String = null, `endid`: java.lang.String = null, `form`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `shape`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Fermata = 
    meibasic.mei.cmn.Fermata.apply(`color`, `endid`, `form`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `place`, `plist`, `shape`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def fileDesc(`corresp`: java.lang.String = null, `label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.header.FileDesc = 
    meibasic.mei.header.FileDesc.apply(`corresp`, `label`, `type`, `xml:id`)(elements*)

  def fing(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.fingering.Fing = 
    meibasic.mei.fingering.Fing.apply(`color`, `dur`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def fingGrp(`dur`: java.lang.String = null, `endid`: java.lang.String = null, `form`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.fingering.FingGrp = 
    meibasic.mei.fingering.FingGrp.apply(`dur`, `endid`, `form`, `label`, `layer`, `plist`, `staff`, `startid`, `tstamp`, `tstamp2`, `type`, `xml:id`)(elements*)

  def gliss(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `endvo`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lform`: java.lang.String = null, `lineheight`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `startvo`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Gliss = 
    meibasic.mei.cmn.Gliss.apply(`color`, `dur`, `endho`, `endid`, `endvo`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `letterspacing`, `lform`, `lineheight`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `plist`, `staff`, `startho`, `startid`, `startvo`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def graceGrp(`attach`: java.lang.String = null, `color`: java.lang.String = null, `grace`: java.lang.String = null, `grace.time`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.GraceGrp = 
    meibasic.mei.cmn.GraceGrp.apply(`attach`, `color`, `grace`, `grace.time`, `label`, `layer`, `staff`, `type`, `xml:id`)(elements*)

  def hairpin(`angle.optimize`: java.lang.String = null, `closed`: java.lang.String = null, `color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `endvo`: java.lang.String = null, `form`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lwidth`: java.lang.String = null, `niente`: java.lang.String = null, `opening`: java.lang.String = null, `opening.vertical`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `startvo`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `val`: java.lang.String = null, `val2`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Hairpin = 
    meibasic.mei.cmn.Hairpin.apply(`angle.optimize`, `closed`, `color`, `dur`, `endho`, `endid`, `endvo`, `form`, `ho`, `label`, `layer`, `lform`, `lsegs`, `lwidth`, `niente`, `opening`, `opening.vertical`, `place`, `plist`, `staff`, `startho`, `startid`, `startvo`, `tstamp`, `tstamp2`, `type`, `val`, `val2`, `vo`, `xml:id`)(elements*)

  def halfmRpt(`color`: java.lang.String = null, `dur`: java.lang.String = null, `expand`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.HalfmRpt = 
    meibasic.mei.cmn.HalfmRpt.apply(`color`, `dur`, `expand`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `staff`, `type`, `vo`, `xml:id`)(elements*)

  def harm(`chordref`: java.lang.String = null, `color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `rendgrid`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.harmony.Harm = 
    meibasic.mei.harmony.Harm.apply(`chordref`, `color`, `dur`, `endho`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `rendgrid`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def harpPedal(`a`: java.lang.String = null, `b`: java.lang.String = null, `c`: java.lang.String = null, `color`: java.lang.String = null, `d`: java.lang.String = null, `e`: java.lang.String = null, `endid`: java.lang.String = null, `f`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `g`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.HarpPedal = 
    meibasic.mei.cmn.HarpPedal.apply(`a`, `b`, `c`, `color`, `d`, `e`, `endid`, `f`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `g`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `place`, `plist`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def instrDef(`azimuth`: java.lang.String = null, `elevation`: java.lang.String = null, `label`: java.lang.String = null, `midi.channel`: java.lang.String = null, `midi.duty`: java.lang.String = null, `midi.instrname`: java.lang.String = null, `midi.instrnum`: java.lang.String = null, `midi.pan`: java.lang.String = null, `midi.patchname`: java.lang.String = null, `midi.patchnum`: java.lang.String = null, `midi.port`: java.lang.String = null, `midi.track`: java.lang.String = null, `midi.volume`: java.lang.String = null, `n`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.midi.InstrDef = 
    meibasic.mei.midi.InstrDef.apply(`azimuth`, `elevation`, `label`, `midi.channel`, `midi.duty`, `midi.instrname`, `midi.instrnum`, `midi.pan`, `midi.patchname`, `midi.patchnum`, `midi.port`, `midi.track`, `midi.volume`, `n`, `type`, `xml:id`)(elements*)

  def label(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Label = 
    meibasic.mei.shared.Label.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def labelAbbr(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.LabelAbbr = 
    meibasic.mei.shared.LabelAbbr.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def layer(`label`: java.lang.String = null, `n`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Layer = 
    meibasic.mei.shared.Layer.apply(`label`, `n`, `type`, `xml:id`)(elements*)

  def lb(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Lb = 
    meibasic.mei.shared.Lb.apply(`label`, `type`, `xml:id`)(elements*)

  def lv(`color`: java.lang.String = null, `curvedir`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `endvo`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lwidth`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `startvo`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Lv = 
    meibasic.mei.cmn.Lv.apply(`color`, `curvedir`, `endho`, `endid`, `endvo`, `ho`, `label`, `layer`, `lform`, `lsegs`, `lwidth`, `plist`, `staff`, `startho`, `startid`, `startvo`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def lyricist(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Lyricist = 
    meibasic.mei.shared.Lyricist.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def mNum(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.MNum = 
    meibasic.mei.cmn.MNum.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `ho`, `label`, `letterspacing`, `lineheight`, `place`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def mRest(`color`: java.lang.String = null, `cue`: java.lang.String = null, `cutout`: java.lang.String = null, `dur`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `oloc`: java.lang.String = null, `ploc`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.MRest = 
    meibasic.mei.cmn.MRest.apply(`color`, `cue`, `cutout`, `dur`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `oloc`, `ploc`, `staff`, `type`, `vo`, `xml:id`)(elements*)

  def mRpt(`color`: java.lang.String = null, `expand`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `num`: java.lang.String = null, `num.place`: java.lang.String = null, `num.visible`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.MRpt = 
    meibasic.mei.cmn.MRpt.apply(`color`, `expand`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `label`, `layer`, `letterspacing`, `lineheight`, `num`, `num.place`, `num.visible`, `staff`, `type`, `xml:id`)(elements*)

  def mdiv(`attacca`: java.lang.String = null, `label`: java.lang.String = null, `n`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Mdiv = 
    meibasic.mei.shared.Mdiv.apply(`attacca`, `label`, `n`, `type`, `xml:id`)(elements*)

  def measure(`label`: java.lang.String = null, `left`: java.lang.String = null, `metcon`: java.lang.String = null, `n`: java.lang.String = null, `right`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Measure = 
    meibasic.mei.cmn.Measure.apply(`label`, `left`, `metcon`, `n`, `right`, `type`, `xml:id`)(elements*)

  def mei(`meiversion`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Mei = 
    meibasic.mei.shared.Mei.apply(`meiversion`, `xml:id`)(elements*)

  def meiHead(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.header.MeiHead = 
    meibasic.mei.header.MeiHead.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def mordent(`accidlower`: java.lang.String = null, `accidlower.ges`: java.lang.String = null, `accidupper`: java.lang.String = null, `accidupper.ges`: java.lang.String = null, `color`: java.lang.String = null, `enclose`: java.lang.String = null, `endid`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `form`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `long`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmnornaments.Mordent = 
    meibasic.mei.cmnornaments.Mordent.apply(`accidlower`, `accidlower.ges`, `accidupper`, `accidupper.ges`, `color`, `enclose`, `endid`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `form`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `long`, `place`, `plist`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def multiRest(`block`: java.lang.String = null, `color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `num`: java.lang.String = null, `num.place`: java.lang.String = null, `num.visible`: java.lang.String = null, `oloc`: java.lang.String = null, `ploc`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `width`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.MultiRest = 
    meibasic.mei.cmn.MultiRest.apply(`block`, `color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `label`, `layer`, `letterspacing`, `lineheight`, `num`, `num.place`, `num.visible`, `oloc`, `ploc`, `staff`, `type`, `width`, `xml:id`)(elements*)

  def multiRpt(`color`: java.lang.String = null, `expand`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `num`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.MultiRpt = 
    meibasic.mei.cmn.MultiRpt.apply(`color`, `expand`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `label`, `layer`, `letterspacing`, `lineheight`, `num`, `staff`, `type`, `xml:id`)(elements*)

  def music(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Music = 
    meibasic.mei.shared.Music.apply(`label`, `type`, `xml:id`)(elements*)

  def note(`breaksec`: java.lang.String = null, `color`: java.lang.String = null, `cue`: java.lang.String = null, `dots`: java.lang.String = null, `dur`: java.lang.String = null, `enclose`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `grace`: java.lang.String = null, `grace.time`: java.lang.String = null, `ho`: java.lang.String = null, `instr`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `oct`: java.lang.String = null, `oct.ges`: java.lang.String = null, `pname`: java.lang.String = null, `pname.ges`: java.lang.String = null, `staff`: java.lang.String = null, `stem.dir`: java.lang.String = null, `stem.len`: java.lang.String = null, `stem.mod`: java.lang.String = null, `tab.course`: java.lang.String = null, `tab.fing`: java.lang.String = null, `tab.fret`: java.lang.String = null, `tab.line`: java.lang.String = null, `tab.string`: java.lang.String = null, `type`: java.lang.String = null, `vel`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Note = 
    meibasic.mei.shared.Note.apply(`breaksec`, `color`, `cue`, `dots`, `dur`, `enclose`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `grace`, `grace.time`, `ho`, `instr`, `label`, `layer`, `letterspacing`, `lineheight`, `oct`, `oct.ges`, `pname`, `pname.ges`, `staff`, `stem.dir`, `stem.len`, `stem.mod`, `tab.course`, `tab.fing`, `tab.fret`, `tab.line`, `tab.string`, `type`, `vel`, `xml:id`)(elements*)

  def octave(`coll`: java.lang.String = null, `color`: java.lang.String = null, `dis`: java.lang.String = null, `dis.place`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Octave = 
    meibasic.mei.cmn.Octave.apply(`coll`, `color`, `dis`, `dis.place`, `dur`, `endho`, `endid`, `extender`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def ornam(`accidlower`: java.lang.String = null, `accidlower.ges`: java.lang.String = null, `accidupper`: java.lang.String = null, `accidupper.ges`: java.lang.String = null, `color`: java.lang.String = null, `dur`: java.lang.String = null, `enclose`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Ornam = 
    meibasic.mei.shared.Ornam.apply(`accidlower`, `accidlower.ges`, `accidupper`, `accidupper.ges`, `color`, `dur`, `enclose`, `endho`, `endid`, `ho`, `label`, `layer`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def pb(`folium`: java.lang.String = null, `label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Pb = 
    meibasic.mei.shared.Pb.apply(`folium`, `label`, `type`, `xml:id`)(elements*)

  def pedal(`color`: java.lang.String = null, `dir`: java.lang.String = null, `endid`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `form`: java.lang.String = null, `func`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lform`: java.lang.String = null, `lineheight`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Pedal = 
    meibasic.mei.cmn.Pedal.apply(`color`, `dir`, `endid`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `form`, `func`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `letterspacing`, `lform`, `lineheight`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def persName(`enddate`: java.lang.String = null, `isodate`: java.lang.String = null, `label`: java.lang.String = null, `notafter`: java.lang.String = null, `notbefore`: java.lang.String = null, `nymref`: java.lang.String = null, `role`: java.lang.String = null, `startdate`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.namesdates.PersName = 
    meibasic.mei.namesdates.PersName.apply(`enddate`, `isodate`, `label`, `notafter`, `notbefore`, `nymref`, `role`, `startdate`, `type`, `xml:id`, `xml:lang`)(elements*)

  def pgFoot(`func`: java.lang.String = null, `halign`: java.lang.String = null, `label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.PgFoot = 
    meibasic.mei.shared.PgFoot.apply(`func`, `halign`, `label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def pgHead(`func`: java.lang.String = null, `halign`: java.lang.String = null, `label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.PgHead = 
    meibasic.mei.shared.PgHead.apply(`func`, `halign`, `label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def pubPlace(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.PubPlace = 
    meibasic.mei.shared.PubPlace.apply(`label`, `type`, `xml:id`, `xml:lang`)(elements*)

  def pubStmt(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.header.PubStmt = 
    meibasic.mei.header.PubStmt.apply(`label`, `type`, `xml:id`)(elements*)

  def refrain(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `voltasym`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.lyrics.Refrain = 
    meibasic.mei.lyrics.Refrain.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `label`, `letterspacing`, `lineheight`, `place`, `type`, `vo`, `voltasym`, `xml:id`, `xml:lang`)(elements*)

  def reh(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Reh = 
    meibasic.mei.cmn.Reh.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `ho`, `label`, `letterspacing`, `lineheight`, `place`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def rend(`altrend`: java.lang.String = null, `color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `halign`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `rend`: java.lang.String = null, `rotation`: java.lang.String = null, `type`: java.lang.String = null, `valign`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null, `xml:space`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Rend = 
    meibasic.mei.shared.Rend.apply(`altrend`, `color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.uri`, `halign`, `label`, `letterspacing`, `lineheight`, `rend`, `rotation`, `type`, `valign`, `xml:id`, `xml:lang`, `xml:space`)(elements*)

  def repeatMark(`color`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `func`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.RepeatMark = 
    meibasic.mei.cmn.RepeatMark.apply(`color`, `dur`, `endho`, `endid`, `extender`, `func`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def respStmt(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.RespStmt = 
    meibasic.mei.shared.RespStmt.apply(`label`, `type`, `xml:id`)(elements*)

  def rest(`breaksec`: java.lang.String = null, `color`: java.lang.String = null, `cue`: java.lang.String = null, `dots`: java.lang.String = null, `dur`: java.lang.String = null, `enclose`: java.lang.String = null, `ho`: java.lang.String = null, `instr`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `oloc`: java.lang.String = null, `ploc`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Rest = 
    meibasic.mei.shared.Rest.apply(`breaksec`, `color`, `cue`, `dots`, `dur`, `enclose`, `ho`, `instr`, `label`, `layer`, `oloc`, `ploc`, `staff`, `type`, `vo`, `xml:id`)(elements*)

  def sb(`fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `form`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Sb = 
    meibasic.mei.shared.Sb.apply(`fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `form`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `label`, `letterspacing`, `lineheight`, `type`, `xml:id`)(elements*)

  def score(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Score = 
    meibasic.mei.shared.Score.apply(`label`, `type`, `xml:id`)(elements*)

  def scoreDef(`keysig`: java.lang.String = null, `label`: java.lang.String = null, `meter.count`: java.lang.String = null, `meter.sym`: java.lang.String = null, `meter.unit`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.ScoreDef = 
    meibasic.mei.shared.ScoreDef.apply(`keysig`, `label`, `meter.count`, `meter.sym`, `meter.unit`, `type`, `xml:id`)(elements*)

  def section(`attacca`: java.lang.String = null, `label`: java.lang.String = null, `restart`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Section = 
    meibasic.mei.shared.Section.apply(`attacca`, `label`, `restart`, `type`, `xml:id`)(elements*)

  def slur(`color`: java.lang.String = null, `curvedir`: java.lang.String = null, `dur`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `endvo`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lwidth`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `startvo`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Slur = 
    meibasic.mei.cmn.Slur.apply(`color`, `curvedir`, `dur`, `endho`, `endid`, `endvo`, `ho`, `label`, `layer`, `lform`, `lsegs`, `lwidth`, `plist`, `staff`, `startho`, `startid`, `startvo`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def space(`compressable`: java.lang.String = null, `cutout`: java.lang.String = null, `dots`: java.lang.String = null, `dur`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Space = 
    meibasic.mei.shared.Space.apply(`compressable`, `cutout`, `dots`, `dur`, `label`, `layer`, `staff`, `type`, `xml:id`)(elements*)

  def staff(`label`: java.lang.String = null, `n`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Staff = 
    meibasic.mei.shared.Staff.apply(`label`, `n`, `type`, `xml:id`)(elements*)

  def staffDef(`clef.dis`: java.lang.String = null, `clef.dis.place`: java.lang.String = null, `clef.line`: java.lang.String = null, `clef.shape`: java.lang.String = null, `instr`: java.lang.String = null, `keysig`: java.lang.String = null, `label`: java.lang.String = null, `lines`: java.lang.String = null, `lines.color`: java.lang.String = null, `lines.visible`: java.lang.String = null, `meter.count`: java.lang.String = null, `meter.sym`: java.lang.String = null, `meter.unit`: java.lang.String = null, `n`: java.lang.String = null, `ppq`: java.lang.String = null, `scale`: java.lang.String = null, `tab.courses`: java.lang.String = null, `tab.strings`: java.lang.String = null, `trans.diat`: java.lang.String = null, `trans.semi`: java.lang.String = null, `tune.Hz`: java.lang.String = null, `tune.pname`: java.lang.String = null, `tune.temper`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.StaffDef = 
    meibasic.mei.shared.StaffDef.apply(`clef.dis`, `clef.dis.place`, `clef.line`, `clef.shape`, `instr`, `keysig`, `label`, `lines`, `lines.color`, `lines.visible`, `meter.count`, `meter.sym`, `meter.unit`, `n`, `ppq`, `scale`, `tab.courses`, `tab.strings`, `trans.diat`, `trans.semi`, `tune.Hz`, `tune.pname`, `tune.temper`, `type`, `xml:id`)(elements*)

  def staffGrp(`bar.thru`: java.lang.String = null, `instr`: java.lang.String = null, `label`: java.lang.String = null, `symbol`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.StaffGrp = 
    meibasic.mei.shared.StaffGrp.apply(`bar.thru`, `instr`, `label`, `symbol`, `type`, `xml:id`)(elements*)

  def string(`accid`: java.lang.String = null, `label`: java.lang.String = null, `oct`: java.lang.String = null, `pname`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.stringtab.String = 
    meibasic.mei.stringtab.String.apply(`accid`, `label`, `oct`, `pname`, `type`, `xml:id`)(elements*)

  def syl(`con`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `halign`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `wordpos`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Syl = 
    meibasic.mei.shared.Syl.apply(`con`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `halign`, `ho`, `label`, `letterspacing`, `lineheight`, `place`, `type`, `vo`, `wordpos`, `xml:id`, `xml:lang`)(elements*)

  def symbol(`color`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `scale`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Symbol = 
    meibasic.mei.shared.Symbol.apply(`color`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `scale`, `type`, `vo`, `xml:id`)(elements*)

  def tabDurSym(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `tab.course`: java.lang.String = null, `tab.fing`: java.lang.String = null, `tab.fret`: java.lang.String = null, `tab.line`: java.lang.String = null, `tab.string`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.stringtab.TabDurSym = 
    meibasic.mei.stringtab.TabDurSym.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `place`, `tab.course`, `tab.fing`, `tab.fret`, `tab.line`, `tab.string`, `type`, `vo`, `xml:id`)(elements*)

  def tabGrp(`dots`: java.lang.String = null, `dur`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `staff`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.stringtab.TabGrp = 
    meibasic.mei.stringtab.TabGrp.apply(`dots`, `dur`, `ho`, `label`, `layer`, `staff`, `type`, `xml:id`)(elements*)

  def tempo(`color`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `func`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `midi.bpm`: java.lang.String = null, `midi.mspb`: java.lang.String = null, `mm`: java.lang.String = null, `mm.dots`: java.lang.String = null, `mm.unit`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Tempo = 
    meibasic.mei.shared.Tempo.apply(`color`, `endho`, `endid`, `extender`, `func`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `lform`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `midi.bpm`, `midi.mspb`, `mm`, `mm.dots`, `mm.unit`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

  def tie(`color`: java.lang.String = null, `curvedir`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `endvo`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lform`: java.lang.String = null, `lsegs`: java.lang.String = null, `lwidth`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `startvo`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Tie = 
    meibasic.mei.cmn.Tie.apply(`color`, `curvedir`, `endho`, `endid`, `endvo`, `ho`, `label`, `layer`, `lform`, `lsegs`, `lwidth`, `plist`, `staff`, `startho`, `startid`, `startvo`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def title(`label`: java.lang.String = null, `level`: java.lang.String = null, `n`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.shared.Title = 
    meibasic.mei.shared.Title.apply(`label`, `level`, `n`, `type`, `xml:id`, `xml:lang`)(elements*)

  def titleStmt(`label`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.header.TitleStmt = 
    meibasic.mei.header.TitleStmt.apply(`label`, `type`, `xml:id`)(elements*)

  def trill(`accidlower`: java.lang.String = null, `accidlower.ges`: java.lang.String = null, `accidupper`: java.lang.String = null, `accidupper.ges`: java.lang.String = null, `color`: java.lang.String = null, `dur`: java.lang.String = null, `enclose`: java.lang.String = null, `endho`: java.lang.String = null, `endid`: java.lang.String = null, `extender`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `lendsym`: java.lang.String = null, `lendsym.size`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lform`: java.lang.String = null, `lineheight`: java.lang.String = null, `lsegs`: java.lang.String = null, `lstartsym`: java.lang.String = null, `lstartsym.size`: java.lang.String = null, `lwidth`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startho`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `tstamp2`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmnornaments.Trill = 
    meibasic.mei.cmnornaments.Trill.apply(`accidlower`, `accidlower.ges`, `accidupper`, `accidupper.ges`, `color`, `dur`, `enclose`, `endho`, `endid`, `extender`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `lendsym`, `lendsym.size`, `letterspacing`, `lform`, `lineheight`, `lsegs`, `lstartsym`, `lstartsym.size`, `lwidth`, `place`, `plist`, `staff`, `startho`, `startid`, `tstamp`, `tstamp2`, `type`, `vo`, `xml:id`)(elements*)

  def tuplet(`bracket.place`: java.lang.String = null, `bracket.visible`: java.lang.String = null, `color`: java.lang.String = null, `dur`: java.lang.String = null, `dur.visible`: java.lang.String = null, `endid`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `num`: java.lang.String = null, `num.format`: java.lang.String = null, `num.place`: java.lang.String = null, `num.visible`: java.lang.String = null, `numbase`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `type`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmn.Tuplet = 
    meibasic.mei.cmn.Tuplet.apply(`bracket.place`, `bracket.visible`, `color`, `dur`, `dur.visible`, `endid`, `label`, `layer`, `num`, `num.format`, `num.place`, `num.visible`, `numbase`, `staff`, `startid`, `type`, `xml:id`)(elements*)

  def turn(`accidlower`: java.lang.String = null, `accidlower.ges`: java.lang.String = null, `accidupper`: java.lang.String = null, `accidupper.ges`: java.lang.String = null, `color`: java.lang.String = null, `delayed`: java.lang.String = null, `enclose`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `form`: java.lang.String = null, `glyph.auth`: java.lang.String = null, `glyph.name`: java.lang.String = null, `glyph.num`: java.lang.String = null, `glyph.uri`: java.lang.String = null, `ho`: java.lang.String = null, `label`: java.lang.String = null, `layer`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `place`: java.lang.String = null, `plist`: java.lang.String = null, `staff`: java.lang.String = null, `startid`: java.lang.String = null, `tstamp`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.cmnornaments.Turn = 
    meibasic.mei.cmnornaments.Turn.apply(`accidlower`, `accidlower.ges`, `accidupper`, `accidupper.ges`, `color`, `delayed`, `enclose`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `form`, `glyph.auth`, `glyph.name`, `glyph.num`, `glyph.uri`, `ho`, `label`, `layer`, `letterspacing`, `lineheight`, `place`, `plist`, `staff`, `startid`, `tstamp`, `type`, `vo`, `xml:id`)(elements*)

  def verse(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `n`: java.lang.String = null, `place`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `voltasym`: java.lang.String = null, `xml:id`: java.lang.String = null)(elements: Element*): meibasic.mei.lyrics.Verse = 
    meibasic.mei.lyrics.Verse.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `label`, `letterspacing`, `lineheight`, `n`, `place`, `type`, `vo`, `voltasym`, `xml:id`)(elements*)

  def volta(`color`: java.lang.String = null, `fontfam`: java.lang.String = null, `fontname`: java.lang.String = null, `fontsize`: java.lang.String = null, `fontstyle`: java.lang.String = null, `fontweight`: java.lang.String = null, `label`: java.lang.String = null, `letterspacing`: java.lang.String = null, `lineheight`: java.lang.String = null, `type`: java.lang.String = null, `vo`: java.lang.String = null, `xml:id`: java.lang.String = null, `xml:lang`: java.lang.String = null)(elements: Element*): meibasic.mei.lyrics.Volta = 
    meibasic.mei.lyrics.Volta.apply(`color`, `fontfam`, `fontname`, `fontsize`, `fontstyle`, `fontweight`, `label`, `letterspacing`, `lineheight`, `type`, `vo`, `xml:id`, `xml:lang`)(elements*)

}
